<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Import-Statements" data-toc-modified-id="Import-Statements-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Import Statements</a></span></li><li><span><a href="#Exploratory-Data-Analysis" data-toc-modified-id="Exploratory-Data-Analysis-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Exploratory Data Analysis</a></span></li><li><span><a href="#Create-df_rape" data-toc-modified-id="Create-df_rape-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Create df_rape</a></span></li><li><span><a href="#Data-Cleanup" data-toc-modified-id="Data-Cleanup-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Data Cleanup</a></span></li><li><span><a href="#Creation-of-datetime-column" data-toc-modified-id="Creation-of-datetime-column-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Creation of datetime column</a></span></li><li><span><a href="#Time-Investigation" data-toc-modified-id="Time-Investigation-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Time Investigation</a></span></li></ul></div>

# Import Statements

In [ ]:
# Note: the 538 article:
# https://projects.fivethirtyeight.com/sexual-assault-victims/

In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import math
import seaborn as sns
import sklearn
from sklearn import linear_model
from sklearn import preprocessing
%matplotlib inline
sns.set_style('white')

In [3]:
# Data from https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Historic/qgea-i56i
df = pd.read_csv('NYPD_Complaint_Data_Historic.csv')

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

# Exploratory Data Analysis

In [4]:
df.head()

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,RPT_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,...,ADDR_PCT_CD,LOC_OF_OCCUR_DESC,PREM_TYP_DESC,PARKS_NM,HADEVELOPT,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon
0,101109527,12/31/2015,23:45:00,NaN,NaN,12/31/2015,113,FORGERY,729.0,"FORGERY,ETC.,UNCLASSIFIED-FELO",...,44.0,INSIDE,BAR/NIGHT CLUB,NaN,NaN,1007314.0,241257.0,40.828848,-73.916661,"(40.828848333, -73.916661142)"
1,153401121,12/31/2015,23:36:00,NaN,NaN,12/31/2015,101,MURDER & NON-NEGL. MANSLAUGHTER,NaN,NaN,...,103.0,OUTSIDE,NaN,NaN,NaN,1043991.0,193406.0,40.697338,-73.784557,"(40.697338138, -73.784556739)"
2,569369778,12/31/2015,23:30:00,NaN,NaN,12/31/2015,117,DANGEROUS DRUGS,503.0,"CONTROLLED SUBSTANCE,INTENT TO",...,28.0,NaN,OTHER,NaN,NaN,999463.0,231690.0,40.802607,-73.945052,"(40.802606608, -73.945051911)"
3,968417082,12/31/2015,23:30:00,NaN,NaN,12/31/2015,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,...,105.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,1060183.0,177862.0,40.654549,-73.726339,"(40.654549444, -73.726338791)"
4,641637920,12/31/2015,23:25:00,12/31/2015,23:30:00,12/31/2015,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,...,13.0,FRONT OF,OTHER,NaN,NaN,987606.0,208148.0,40.738002,-73.987891,"(40.7380024, -73.98789129)"

In [5]:
df

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,RPT_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,...,ADDR_PCT_CD,LOC_OF_OCCUR_DESC,PREM_TYP_DESC,PARKS_NM,HADEVELOPT,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon
0,101109527,12/31/2015,23:45:00,NaN,NaN,12/31/2015,113,FORGERY,729.0,"FORGERY,ETC.,UNCLASSIFIED-FELO",...,44.0,INSIDE,BAR/NIGHT CLUB,NaN,NaN,1007314.0,241257.0,40.828848,-73.916661,"(40.828848333, -73.916661142)"
1,153401121,12/31/2015,23:36:00,NaN,NaN,12/31/2015,101,MURDER & NON-NEGL. MANSLAUGHTER,NaN,NaN,...,103.0,OUTSIDE,NaN,NaN,NaN,1043991.0,193406.0,40.697338,-73.784557,"(40.697338138, -73.784556739)"
2,569369778,12/31/2015,23:30:00,NaN,NaN,12/31/2015,117,DANGEROUS DRUGS,503.0,"CONTROLLED SUBSTANCE,INTENT TO",...,28.0,NaN,OTHER,NaN,NaN,999463.0,231690.0,40.802607,-73.945052,"(40.802606608, -73.945051911)"
3,968417082,12/31/2015,23:30:00,NaN,NaN,12/31/2015,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,...,105.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,1060183.0,177862.0,40.654549,-73.726339,"(40.654549444, -73.726338791)"
4,641637920,12/31/2015,23:25:00,12/31/2015,23:30:00,12/31/2015,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,...,13.0,FRONT OF,OTHER,NaN,NaN,987606.0,208148.0,40.738002,-73.987891,"(40.7380024, -73.98789129)"
5,365661343,12/31/2015,23:18:00,12/31/2015,23:25:00,12/31/2015,106,FELONY ASSAULT,109.0,"ASSAULT 2,1,UNCLASSIFIED",...,71.0,FRONT OF,DRUG STORE,NaN,NaN,996149.0,181562.0,40.665023,-73.957111,"(40.665022689, -73.957110763)"
6,608231454,12/31/2015,23:15:00,NaN,NaN,12/31/2015,235,DANGEROUS DRUGS,511.0,"CONTROLLED SUBSTANCE, POSSESSI",...,7.0,OPPOSITE OF,STREET,NaN,NaN,987373.0,201662.0,40.720200,-73.988735,"(40.720199996, -73.988735082)"
7,265023856,12/31/2015,23:15:00,12/31/2015,23:15:00,12/31/2015,118,DANGEROUS WEAPONS,792.0,WEAPONS POSSESSION 1 & 2,...,46.0,FRONT OF,STREET,NaN,NaN,1009041.0,247401.0,40.845707,-73.910398,"(40.845707148, -73.910398033)"
8,989238731,12/31/2015,23:15:00,12/31/2015,23:30:00,12/31/2015,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,...,48.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,1014154.0,251416.0,40.856711,-73.891900,"(40.856711291, -73.891899956)"
9,415095955,12/31/2015,23:10:00,12/31/2015,23:10:00,12/31/2015,341,PETIT LARCENY,338.0,"LARCENY,PETIT FROM BUILDING,UN",...,19.0,INSIDE,DRUG STORE,NaN,NaN,994327.0,218211.0,40.765618,-73.963623,"(40.765617688, -73.96362342)"
10,731283092,12/31/2015,23:05:00,12/31/2015,23:15:00,12/31/2015,341,PETIT LARCENY,343.0,"LARCENY,PETIT OF BICYCLE",...,41.0,INSIDE,FAST FOOD,NaN,NaN,1014216.0,238784.0,40.822040,-73.891732,"(40.822039935, -73.891732267)"
11,178090167,12/31/2015,23:00:00,12/31/2015,23:05:00,12/31/2015,341,PETIT LARCENY,338.0,"LARCENY,PETIT FROM BUILDING,UN",...,13.0,INSIDE,RESTAURANT/DINER,NaN,NaN,988113.0,206263.0,40.732828,-73.986063,"(40.732828332, -73.986062857)"
12,898496564,12/31/2015,23:00:00,NaN,NaN,12/31/2015,109,GRAND LARCENY,406.0,"LARCENY,GRAND FROM PERSON, BAG OPEN/DIP",...,14.0,NaN,STREET,NaN,NaN,987215.0,215403.0,40.757916,-73.989299,"(40.757915693, -73.98929902)"
13,566081066,12/31/2015,23:00:00,NaN,NaN,12/31/2015,109,GRAND LARCENY,415.0,"LARCENY,GRAND FROM PERSON,PICK",...,14.0,NaN,STREET,NaN,NaN,987215.0,215403.0,40.757916,-73.989299,"(40.757915693, -73.98929902)"
14,584555879,12/31/2015,23:00:00,NaN,NaN,12/31/2015,113,FORGERY,729.0,"FORGERY,ETC.,UNCLASSIFIED-FELO",...,67.0,NaN,STREET,NaN,NaN,1004325.0,174113.0,40.644562,-73.927662,"(40.644562053, -73.92766205)"
15,715942154,12/31/2015,23:00:00,12/31/2015,23:05:00,12/31/2015,105,ROBBERY,386.0,"ROBBERY,PERSONAL ELECTRONIC DEVICE",...,103.0,INSIDE,BAR/NIGHT CLUB,NaN,NaN,1044662.0,197327.0,40.708096,-73.782102,"(40.708095777, -73.78210174)"
16,338440707,12/31/2015,23:00:00,12/31/2015,23:10:00,12/31/2015,109,GRAND LARCENY,411.0,"LARCENY,GRAND FROM EATERY, UNATTENDED",...,17.0,INSIDE,RESTAURANT/DINER,NaN,NaN,993034.0,214414.0,40.755197,-73.968296,"(40.755197275, -73.968296117)"
17,433257334,12/31/2015,23:00:00,12/31/2015,23:05:00,12/31/2015,359,OFFENSES AGAINST PUBLIC ADMINI,748.0,"CONTEMPT,CRIMINAL",...,48.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,1014139.0,251858.0,40.857924,-73.891952,"(40.857924499, -73.89195221)"
18,761004485,12/31/2015,23:00:00,12/31/2015,23:05:00,12/31/2015,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,...,61.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,993932.0,160170.0,40.606309,-73.965133,"(40.606308897, -73.965132766)"
19,234892198,12/31/2015,22:55:00,12/31/2015,23:10:00,12/31/2015,351,CRIMINAL MISCHIEF & RELATED OF,259.0,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",...,102.0,FRONT OF,DRY CLEANER/LAUNDRY,NaN,NaN,1022298.0,186863.0,40.679499,-73.862825,"(40.679498977, -73.862825258)"
20,231688534,12/31/2015,22:53:00,12/31/2015,22:55:00,12/31/2015,235,DANGEROUS DRUGS,511.0,"CONTROLLED SUBSTANCE, POSSESSI",...,71.0,NaN,STREET,NaN,NaN,995387.0,178144.0,40.655642,-73.959863,"(40.655642023, -73.959863084)"
21,340513307,04/06/2015,12:00:00,04/10/2015,18:00:00,12/21/2015,104,RAPE,155.0,RAPE 2,...,110.0,INSIDE,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,704037588,12/31/2015,22:50:00,12/31/2015,22:57:00,12/31/2015,235,DANGEROUS DRUGS,511.0,"CONTROLLED SUBSTANCE, POSSESSI",...,108.0,NaN,STREET,NaN,NaN,1012629.0,212283.0,40.749307,-73.897578,"(40.749307045, -73.897578152)"
23,549465293,12/31/2015,22:50:00,12/31/2015,22:58:00,12/31/2015,106,FELONY ASSAULT,105.0,STRANGULATION 1ST,...,75.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,1018309.0,183847.0,40.671237,-73.877222,"(40.67123699, -73.877222202)"
24,693907266,12/31/2015,22:45:00,12/31/2015,22:50:00,12/31/2015,118,DANGEROUS WEAPONS,793.0,WEAPONS POSSESSION 3,...,73.0,FRONT OF,PUBLIC BUILDING,NaN,NaN,1008202.0,179835.0,40.660258,-73.913671,"(40.660258056, -73.913671137)"
25,371600116,12/31/2015,22:45:00,12/31/2015,22:50:00,12/31/2015,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,...,60.0,FRONT OF,RESTAURANT/DINER,NaN,NaN,992099.0,152792.0,40.586060,-73.971743,"(40.586059585, -73.971742687)"
26,359273994,12/31/2015,22:45:00,12/31/2015,22:55:00,12/31/2015,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,...,68.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,978368.0,169905.0,40.633033,-74.021193,"(40.633032786, -74.02119331)"
27,415805453,12/31/2015,22:45:00,NaN,NaN,12/31/2015,118,DANGEROUS WEAPONS,793.0,WEAPONS POSSESSION 3,...,75.0,NaN,STREET,NaN,NaN,1014100.0,183318.0,40.669800,-73.892398,"(40.669800195, -73.892397547)"
28,251546004,12/31/2015,22:40:00,12/31/2015,22:50:00,12/31/2015,235,DANGEROUS DRUGS,567.0,"MARIJUANA, POSSESSION 4 & 5",...,79.0,INSIDE,RESIDENCE - PUBLIC HOUSING,NaN,MARCY,998273.0,193029.0,40.696494,-73.949431,"(40.696493892, -73.949430815)"
29,624630216,12/31/2015,22:40:00,12/31/2015,22:56:00,12/31/2015,347,INTOXICATED & IMPAIRED DRIVING,905.0,"INTOXICATED DRIVING,ALCOHOL",...,121.0,NaN,STREET,NaN,NaN,940334.0,166826.0,40.624475,-74.158203,"(40.624474678, -74.158203285)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6048766,257531441,12/16/2016,15:25:00,12/16/2016,15:30:00,01/01/2017,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,...,75.0,NaN,RESTAURANT/DINER,NaN,NaN,1014820.0,179358.0,40.658928,-73.889820,"(40.658928422, -73.889820034)"
6048767,924787396,12/15/2016,22:01:00,12/15/2016,22:03:00,01/01/2017,341,PETIT LARCENY,339.0,"LARCENY,PETIT FROM OPEN AREAS,",...,61.0,FRONT OF,RESIDENCE-HOUSE,NaN,NaN,997921.0,161182.0,40.609081,-73.950765,"(40.609081374, -73.95076477)"
6048768,626569375,12/10/2016,19:00:00,12/11/2016,12:00:00,01/01/2017,351,CRIMINAL MISCHIEF & RELATED OF,254.0,"MISCHIEF, CRIMINAL 4, OF MOTOR",...,63.0,FRONT OF,STREET,NaN,NaN,1006769.0,167075.0,40.625238,-73.918879,"(40.625238367, -73.918878692)"
6048769,514844467,12/10/2016,14:00:00,12/10/2016,15:00:00,01/01/2017,112,THEFT-FRAUD,739.0,"FRAUD,UNCLASSIFIED-FELONY",...,52.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,1018531.0,258225.0,40.875384,-73.876043,"(40.875384004, -73.876042504)"
6048770,376183862,12/09/2016,01:00:00,12/14/2016,22:00:00,01/01/2017,351,CRIMINAL MISCHIEF & RELATED OF,258.0,"CRIMINAL MISCHIEF 4TH, GRAFFIT",...,121.0,REAR OF,RESTAURANT/DINER,NaN,NaN,938881.0,167697.0,40.626858,-74.163443,"(40.626858064, -74.163443377)"
6048771,419208730,12/05/2016,23:00:00,12/05/2016,23:10:00,01/01/2017,106,FELONY ASSAULT,109.0,"ASSAULT 2,1,UNCLASSIFIED",...,63.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,1012234.0,163622.0,40.615745,-73.899206,"(40.615745029, -73.89920583)"
6048772,564382220,12/04/2016,20:00:00,12/06/2016,08:00:00,01/01/2017,351,CRIMINAL MISCHIEF & RELATED OF,258.0,"CRIMINAL MISCHIEF 4TH, GRAFFIT",...,121.0,REAR OF,CHAIN STORE,NaN,NaN,942825.0,166367.0,40.623227,-74.149227,"(40.623226819, -74.149226973)"
6048773,421318231,12/03/2016,16:00:00,01/01/2017,10:00:00,01/01/2017,341,PETIT LARCENY,321.0,"LARCENY,PETIT FROM AUTO",...,52.0,OPPOSITE OF,STREET,NaN,NaN,1019388.0,259017.0,40.877554,-73.872939,"(40.877554428, -73.872939471)"
6048774,736943522,12/03/2016,15:00:00,12/20/2016,15:00:00,01/01/2017,109,GRAND LARCENY,422.0,"LARCENY,GRAND BY OPEN CREDIT CARD (NEW ACCT)",...,112.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,1025551.0,198862.0,40.712419,-73.851024,"(40.712418824, -73.851023519)"
6048775,264440192,12/03/2016,03:30:00,12/03/2016,03:40:00,01/01/2017,578,HARRASSMENT 2,638.0,"HARASSMENT,SUBD 3,4,5",...,19.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,995728.0,216993.0,40.762273,-73.958568,"(40.762272884, -73.958567881)"
6048776,832707021,12/01/2016,16:00:00,01/08/2017,11:50:00,01/01/2017,341,PETIT LARCENY,339.0,"LARCENY,PETIT FROM OPEN AREAS,",...,1.0,NaN,TRANSIT - NYC SUBWAY,NaN,NaN,981005.0,197131.0,40.707763,-74.011706,"(40.707763436, -74.011705749)"
6048777,781849083,11/30/2016,21:00:00,11/30/2016,21:15:00,01/01/2017,678,MISCELLANEOUS PENAL LAW,201.0,"TRESPASS 4,CRIMINAL SUB 2",...,70.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,993121.0,170010.0,40.633319,-73.968041,"(40.633318501, -73.968040566)"
6048778,564963325,11/16/2016,00:30:00,11/16/2016,01:00:00,01/01/2017,351,CRIMINAL MISCHIEF & RELATED OF,259.0,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",...,45.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,1031944.0,250456.0,40.853998,-73.827597,"(40.853998204, -73.82759694)"
6048779,120230345,10/27/2016,00:01:00,10/27/2016,23:00:00,01/01/2017,341,PETIT LARCENY,339.0,"LARCENY,PETIT FROM OPEN AREAS,",...,47.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,1030439.0,263921.0,40.890963,-73.832944,"(40.890963439, -73.832944385)"
6048780,227833735,10/21/2016,13:00:00,10/21/2016,13:15:00,01/01/2017,578,HARRASSMENT 2,637.0,"HARASSMENT,SUBD 1,CIVILIAN",...,66.0,INSIDE,OTHER,NaN,NaN,991675.0,161586.0,40.610198,-73.973260,"(40.610197706, -73.97325955)"
6048781,548130183,10/13/2016,01:30:00,10/13/2016,02:00:00,01/01/2017,106,FELONY ASSAULT,109.0,"ASSAULT 2,1,UNCLASSIFIED",...,73.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,1011054.0,182428.0,40.667367,-73.903381,"(40.66736709, -73.90338136)"
6048782,693530867,10/12/2016,10:00:00,NaN,NaN,01/01/2017,341,PETIT LARCENY,338.0,"LARCENY,PETIT FROM BUILDING,UN",...,9.0,INSIDE,CHAIN STORE,NaN,NaN,986578.0,204044.0,40.726738,-73.991602,"(40.726738256, -73.991602257)"
6048783,637293210,10/05/2016,00:00:00,01/01/2017,21:16:00,01/01/2017,112,THEFT-FRAUD,739.0,"FRAUD,UNCLASSIFIED-FELONY",...,62.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,990374.0,163503.0,40.615460,-73.977943,"(40.615460472, -73.977943495)"
6048784,766452024,10/04/2016,09:00:00,10/04/2016,09:30:00,01/01/2017,109,GRAND LARCENY,432.0,"LARCENY,GRAND BY IDENTITY THEFT-UNCLASSIFIED",...,71.0,INSIDE,OTHER HOUSE OF WORSHIP,NaN,NaN,996588.0,181055.0,40.663630,-73.955529,"(40.663630486, -73.955529289)"
6048785,486460516,07/01/2016,00:01:00,01/01/2017,16:40:00,01/01/2017,361,OFF. AGNST PUB ORD SENSBLTY &,639.0,AGGRAVATED HARASSMENT 2,...,90.0,INSIDE,RESIDENCE - PUBLIC HOUSING,NaN,BUSHWICK,1001438.0,194908.0,40.701646,-73.938012,"(40.701645727, -73.938012201)"
6048786,977298651,05/29/2016,12:29:00,NaN,NaN,01/01/2017,361,OFF. AGNST PUB ORD SENSBLTY &,639.0,AGGRAVATED HARASSMENT 2,...,75.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,1015630.0,182164.0,40.666627,-73.886888,"(40.666627433, -73.886887549)"
6048787,243551498,04/01/2016,00:00:00,06/01/2016,23:59:00,01/01/2017,116,SEX CRIMES,177.0,SEXUAL ABUSE,...,44.0,INSIDE,RESIDENCE - PUBLIC HOUSING,NaN,CLAREMONT REHAB (GROUP 3),NaN,NaN,NaN,NaN,NaN
6048788,181622017,03/01/2016,13:00:00,01/01/2017,22:30:00,01/01/2017,578,HARRASSMENT 2,638.0,"HARASSMENT,SUBD 3,4,5",...,19.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,998840.0,224118.0,40.781825,-73.947319,"(40.781824561, -73.947318642)"
6048789,626739714,01/01/2016,06:10:00,01/01/2017,06:12:00,01/01/2017,348,VEHICLE AND TRAFFIC LAWS,916.0,LEAVING SCENE-ACCIDENT-PERSONA,...,46.0,NaN,STREET,NaN,NaN,1011511.0,248284.0,40.848123,-73.901467,"(40.848123442, -73.901466999)"
6048790,492890715,01/01/2016,06:00:00,01/01/2017,06:15:00,01/01/2017,341,PETIT LARCENY,313.0,"LARCENY,PETIT BY FALSE PROMISE",...,77.0,NaN,STREET,NaN,NaN,1001868.0,183705.0,40.670895,-73.936491,"(40.670895214, -73.936490681)"
6048791,657605513,01/01/2016,04:00:00,01/01/2016,04:10:00,01/01/2017,351,CRIMINAL MISCHIEF & RELATED OF,259.0,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",...,106.0,FRONT OF,STREET,NaN,NaN,1038579.0,185782.0,40.676447,-73.804136,"(40.676446932, -73.804135509)"
6048792,553117159,01/01/2016,03:00:00,01/01/2017,07:00:00,01/01/2017,341,PETIT LARCENY,338.0,"LARCENY,PETIT FROM BUILDING,UN",...,94.0,INSIDE,BAR/NIGHT CLUB,NaN,NaN,995698.0,202372.0,40.722142,-73.958701,"(40.722141921, -73.958701058)"
6048793,473961688,12/01/2015,00:00:00,12/01/2015,00:00:00,01/01/2017,112,THEFT-FRAUD,739.0,"FRAUD,UNCLASSIFIED-FELONY",...,47.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,1024111.0,263586.0,40.890075,-73.855834,"(40.890074824, -73.855833541)"
6048794,479719874,07/01/2015,18:05:00,07/01/2015,18:15:00,01/01/2017,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,...,62.0,FRONT OF,SMALL MERCHANT,NaN,NaN,989361.0,162863.0,40.613704,-73.981593,"(40.613704446, -73.981592689)"
6048795,329336049,10/01/2012,00:01:00,10/01/2012,00:01:00,01/01/2017,104,RAPE,153.0,RAPE 3,...,24.0,INSIDE,RESIDENCE - PUBLIC HOUSING,NaN,DOUGLASS,NaN,NaN,NaN,NaN,NaN

In [6]:
df.dtypes

CMPLNT_NUM             int64
CMPLNT_FR_DT          object
CMPLNT_FR_TM          object
CMPLNT_TO_DT          object
CMPLNT_TO_TM          object
RPT_DT                object
KY_CD                  int64
OFNS_DESC             object
PD_CD                float64
PD_DESC               object
CRM_ATPT_CPTD_CD      object
LAW_CAT_CD            object
JURIS_DESC            object
BORO_NM               object
ADDR_PCT_CD          float64
LOC_OF_OCCUR_DESC     object
PREM_TYP_DESC         object
PARKS_NM              object
HADEVELOPT            object
X_COORD_CD           float64
Y_COORD_CD           float64
Latitude             float64
Longitude            float64
Lat_Lon               object
dtype: object

In [7]:
df['OFNS_DESC'].value_counts()

PETIT LARCENY                           987326
HARRASSMENT 2                           736479
ASSAULT 3 & RELATED OFFENSES            625624
CRIMINAL MISCHIEF & RELATED OF          603977
GRAND LARCENY                           516544
DANGEROUS DRUGS                         392992
OFF. AGNST PUB ORD SENSBLTY &           327716
ROBBERY                                 228220
FELONY ASSAULT                          224921
BURGLARY                                216439
MISCELLANEOUS PENAL LAW                 145888
DANGEROUS WEAPONS                       143395
OFFENSES AGAINST PUBLIC ADMINI          117062
GRAND LARCENY OF MOTOR VEHICLE          114071
INTOXICATED & IMPAIRED DRIVING           85349
CRIMINAL TRESPASS                        74083
VEHICLE AND TRAFFIC LAWS                 72173
SEX CRIMES                               68020
THEFT-FRAUD                              66184
FORGERY                                  61024
FRAUDS                                   38308
POSSESSION OF STOLEN PROPERTY            33169
OFFENSES INVOLVING FRAUD                 20143
UNAUTHORIZED USE OF A VEHICLE            17301
RAPE                                     16673
ARSON                                    15439
OFFENSES AGAINST THE PERSON              14914
ADMINISTRATIVE CODE                      13274
OTHER OFFENSES RELATED TO THEF           12962
OTHER STATE LAWS (NON PENAL LA            6075
                                         ...
ALCOHOLIC BEVERAGE CONTROL LAW             994
DISORDERLY CONDUCT                         932
OFFENSES AGAINST PUBLIC SAFETY             913
CHILD ABANDONMENT/NON SUPPORT              406
JOSTLING                                   386
AGRICULTURE & MRKTS LAW-UNCLASSIFIED       347
OTHER STATE LAWS                           264
LOITERING/GAMBLING (CARDS, DIC             234
ENDAN WELFARE INCOMP                       203
ESCAPE 3                                   185
ANTICIPATORY OFFENSES                      102
HOMICIDE-NEGLIGENT-VEHICLE                  97
NEW YORK CITY HEALTH CODE                   85
UNLAWFUL POSS. WEAP. ON SCHOOL              64
HOMICIDE-NEGLIGENT,UNCLASSIFIE              52
DISRUPTION OF A RELIGIOUS SERV              51
INTOXICATED/IMPAIRED DRIVING                50
NYS LAWS-UNCLASSIFIED VIOLATION             26
LOITERING FOR DRUG PURPOSES                 23
LOITERING                                   23
KIDNAPPING                                  21
ADMINISTRATIVE CODES                        19
LOITERING/DEVIATE SEX                       16
OTHER TRAFFIC INFRACTION                    13
FORTUNE TELLING                             11
OTHER STATE LAWS (NON PENAL LAW)            10
ABORTION                                     5
OFFENSES AGAINST MARRIAGE UNCL               3
UNDER THE INFLUENCE OF DRUGS                 3
KIDNAPPING AND RELATED OFFENSES              2
Name: OFNS_DESC, Length: 70, dtype: int64

In [8]:
# Identifying attempted rape vs completed rape
df.loc[df['OFNS_DESC'] == 'RAPE', 'CRM_ATPT_CPTD_CD'].value_counts()

COMPLETED    14843
ATTEMPTED     1830
Name: CRM_ATPT_CPTD_CD, dtype: int64

# Create df_rape

In [9]:
df_rape = df.loc[df['OFNS_DESC'] == 'RAPE']

In [10]:
df_rape.shape

(16673, 24)

In [11]:
# The outcome variable, rape completed vs attempted
df_rape['CRM_ATPT_CPTD_CD'].value_counts()

COMPLETED    14843
ATTEMPTED     1830
Name: CRM_ATPT_CPTD_CD, dtype: int64

In [12]:
df_rape.isnull().sum()

CMPLNT_NUM               0
CMPLNT_FR_DT             1
CMPLNT_FR_TM             0
CMPLNT_TO_DT          3604
CMPLNT_TO_TM          3598
RPT_DT                   0
KY_CD                    0
OFNS_DESC                0
PD_CD                    0
PD_DESC                  0
CRM_ATPT_CPTD_CD         0
LAW_CAT_CD               0
JURIS_DESC               0
BORO_NM                  4
ADDR_PCT_CD              4
LOC_OF_OCCUR_DESC     1555
PREM_TYP_DESC           63
PARKS_NM             16583
HADEVELOPT           15538
X_COORD_CD           16673
Y_COORD_CD           16673
Latitude             16673
Longitude            16673
Lat_Lon              16673
dtype: int64

In [13]:
# NULL VALUES TO WATCH OUT FOR

In [14]:
(df_rape['CMPLNT_FR_TM'] == '24:00:00').value_counts(sort = True)

False    16654
True        19
Name: CMPLNT_FR_TM, dtype: int64

In [15]:
(df_rape['CMPLNT_TO_TM'] == '24:00:00').value_counts(sort = True)

False    16614
True        59
Name: CMPLNT_TO_TM, dtype: int64

In [16]:
df_rape.loc[df_rape['CMPLNT_FR_DT'].isna()]

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,RPT_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,...,ADDR_PCT_CD,LOC_OF_OCCUR_DESC,PREM_TYP_DESC,PARKS_NM,HADEVELOPT,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon
1008394,155379861,NaN,06:00:00,12/02/2013,06:30:00,12/02/2013,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,90.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Data Cleanup

In [17]:
# In situations where the From Date is Null, change to to date

In [18]:
# Get rid of a troublesome na
df_rape.loc[df_rape['CMPLNT_FR_DT'].isna(), 'CMPLNT_FR_DT'] = df_rape.loc[df_rape['CMPLNT_FR_DT'].isna(), 'CMPLNT_TO_DT']

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [19]:
df_rape.loc[df_rape['CMPLNT_FR_DT'].isna()]

Empty DataFrame
Columns: [CMPLNT_NUM, CMPLNT_FR_DT, CMPLNT_FR_TM, CMPLNT_TO_DT, CMPLNT_TO_TM, RPT_DT, KY_CD, OFNS_DESC, PD_CD, PD_DESC, CRM_ATPT_CPTD_CD, LAW_CAT_CD, JURIS_DESC, BORO_NM, ADDR_PCT_CD, LOC_OF_OCCUR_DESC, PREM_TYP_DESC, PARKS_NM, HADEVELOPT, X_COORD_CD, Y_COORD_CD, Latitude, Longitude, Lat_Lon]
Index: []

[0 rows x 24 columns]

In [20]:
# Get rid of troublesome 24:00:00 values in 'From Time'
df_rape.loc[df_rape['CMPLNT_FR_TM'] == '24:00:00', 'CMPLNT_FR_TM'] = '23:59:59'

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [21]:
# Get rid of troublesome 24:00:00 values in 'To Time'
df_rape.loc[df_rape['CMPLNT_TO_TM'] == '24:00:00', 'CMPLNT_TO_TM'] = '23:59:59'

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [22]:
# Check cells
df_rape.sort_values(by='CMPLNT_FR_TM', ascending=False)

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,RPT_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,...,ADDR_PCT_CD,LOC_OF_OCCUR_DESC,PREM_TYP_DESC,PARKS_NM,HADEVELOPT,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon
3466499,829061498,06/01/2002,23:59:59,01/06/2009,15:35:00,01/21/2009,104,RAPE,157.0,RAPE 1,...,122.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3894448,268184195,03/30/2008,23:59:59,NaN,NaN,03/31/2008,104,RAPE,157.0,RAPE 1,...,34.0,INSIDE,RESIDENCE - PUBLIC HOUSING,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3659304,674449658,11/28/2007,23:59:59,NaN,NaN,09/05/2008,104,RAPE,153.0,RAPE 3,...,120.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3838102,937145860,10/12/2007,23:59:59,NaN,NaN,05/09/2008,104,RAPE,157.0,RAPE 1,...,6.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3379603,282308644,01/01/2004,23:59:59,12/31/2004,23:59:00,03/26/2009,104,RAPE,157.0,RAPE 1,...,67.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3601184,357409136,01/01/2007,23:59:59,10/13/2008,23:59:59,10/14/2008,104,RAPE,157.0,RAPE 1,...,34.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3441876,965083518,11/01/2008,23:59:59,11/15/2008,23:59:59,02/09/2009,104,RAPE,157.0,RAPE 1,...,105.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3179713,678406708,04/01/2004,23:59:59,06/01/2005,23:59:00,08/12/2009,104,RAPE,157.0,RAPE 1,...,113.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4153011,833029701,08/29/2007,23:59:59,NaN,NaN,10/03/2007,104,RAPE,157.0,RAPE 1,...,47.0,INSIDE,RESIDENCE - PUBLIC HOUSING,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4011256,266934295,10/31/2007,23:59:59,NaN,NaN,01/09/2008,104,RAPE,157.0,RAPE 1,...,70.0,NaN,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3448223,742908077,05/01/2008,23:59:59,01/19/2009,23:59:00,02/04/2009,104,RAPE,157.0,RAPE 1,...,120.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3841346,635227790,08/01/2006,23:59:59,09/30/2006,23:59:59,05/07/2008,104,RAPE,157.0,RAPE 1,...,123.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3372363,486159316,03/28/2009,23:59:59,NaN,NaN,03/31/2009,104,RAPE,153.0,RAPE 3,...,43.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3764810,495193568,06/01/2007,23:59:59,06/12/2008,23:59:00,06/27/2008,104,RAPE,157.0,RAPE 1,...,120.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3439084,763217678,09/01/2008,23:59:59,01/12/2009,23:59:59,02/11/2009,104,RAPE,153.0,RAPE 3,...,120.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3639701,550075977,07/27/2006,23:59:59,09/01/2006,00:01:00,09/18/2008,104,RAPE,157.0,RAPE 1,...,34.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4100307,920549674,08/01/2000,23:59:59,NaN,NaN,11/06/2007,104,RAPE,157.0,RAPE 1,...,67.0,NaN,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4018704,150676051,02/01/2007,23:59:59,NaN,NaN,01/04/2008,104,RAPE,155.0,RAPE 2,...,120.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3725023,413481078,06/25/2005,23:59:59,NaN,NaN,07/24/2008,104,RAPE,157.0,RAPE 1,...,49.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1518351,727158082,09/27/2012,23:59:00,09/28/2012,06:00:00,11/21/2012,104,RAPE,157.0,RAPE 1,...,94.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2736809,616333067,10/31/2009,23:59:00,NaN,NaN,06/25/2010,104,RAPE,153.0,RAPE 3,...,120.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3187087,626967878,11/07/2007,23:59:00,NaN,NaN,08/07/2009,104,RAPE,157.0,RAPE 1,...,34.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1338629,147330787,04/10/2013,23:59:00,04/11/2013,00:30:00,04/11/2013,104,RAPE,157.0,RAPE 1,...,79.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
566902,728878791,10/18/2014,23:59:00,NaN,NaN,10/21/2014,104,RAPE,153.0,RAPE 3,...,109.0,INSIDE,HOTEL/MOTEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4947327,273728156,09/01/2005,23:59:00,11/30/2005,23:59:00,04/18/2006,104,RAPE,153.0,RAPE 3,...,101.0,INSIDE,RESIDENCE - PUBLIC HOUSING,NaN,REDFERN,NaN,NaN,NaN,NaN,NaN
2826900,177880184,04/23/2010,23:59:00,04/24/2010,01:00:00,04/24/2010,104,RAPE,157.0,RAPE 1,...,20.0,FRONT OF,CHURCH,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4613918,335325175,11/23/2006,23:59:00,11/24/2006,00:30:00,11/24/2006,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,103.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2812754,703020324,05/03/2010,23:59:00,NaN,NaN,05/04/2010,104,RAPE,157.0,RAPE 1,...,61.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1106634,169795668,11/01/2012,23:59:00,09/23/2013,00:01:00,09/23/2013,104,RAPE,155.0,RAPE 2,...,67.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
508653,659693240,02/22/2011,23:59:00,12/01/2014,23:59:00,12/05/2014,104,RAPE,157.0,RAPE 1,...,63.0,FRONT OF,STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5462811,853818171,04/04/2016,00:00:00,04/04/2016,01:40:00,04/04/2016,104,RAPE,157.0,RAPE 1,...,77.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4885960,895930996,03/25/2006,00:00:00,03/31/2006,23:59:00,05/29/2006,104,RAPE,157.0,RAPE 1,...,101.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4881299,684942395,03/28/2006,00:00:00,05/26/2006,00:00:00,06/01/2006,104,RAPE,153.0,RAPE 3,...,79.0,INSIDE,PUBLIC BUILDING,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3571110,253604088,11/03/2008,00:00:00,NaN,NaN,11/03/2008,104,RAPE,153.0,RAPE 3,...,112.0,NaN,STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5465499,408663736,04/01/2016,00:00:00,04/02/2016,00:00:00,04/02/2016,104,RAPE,155.0,RAPE 2,...,44.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169386,638542036,09/01/2013,00:00:00,03/31/2015,00:00:00,08/03/2015,104,RAPE,153.0,RAPE 3,...,61.0,NaN,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5858634,327098060,04/13/2017,00:00:00,04/13/2017,21:55:00,06/03/2017,104,RAPE,157.0,RAPE 1,...,79.0,INSIDE,PARK/PLAYGROUND,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5857454,352529291,02/01/2000,00:00:00,12/03/2007,00:00:00,06/04/2017,104,RAPE,157.0,RAPE 1,...,67.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4861911,437708152,06/11/2005,00:00:00,06/11/2006,20:00:00,06/14/2006,104,RAPE,153.0,RAPE 3,...,101.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1176925,601772887,06/01/2013,00:00:00,07/25/2013,23:59:00,08/05/2013,104,RAPE,157.0,RAPE 1,...,52.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4860141,378404074,05/15/2006,00:00:00,NaN,NaN,06/15/2006,104,RAPE,157.0,RAPE 1,...,100.0,INSIDE,RESIDENCE - PUBLIC HOUSING,NaN,HAMMEL,NaN,NaN,NaN,NaN,NaN
5473438,470565157,10/02/2008,00:00:00,NaN,NaN,03/27/2016,104,RAPE,157.0,RAPE 1,...,67.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1181155,789651806,12/01/2012,00:00:00,08/02/2013,23:59:00,08/02/2013,104,RAPE,153.0,RAPE 3,...,41.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1184968,354837587,07/30/2013,00:00:00,07/30/2013,03:00:00,07/30/2013,104,RAPE,157.0,RAPE 1,...,67.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5843928,236476067,02/01/2016,00:00:00,02/28/2016,23:59:00,06/14/2017,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,48.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1185483,238629118,04/01/2013,00:00:00,05/31/2013,23:59:00,07/30/2013,104,RAPE,155.0,RAPE 2,...,18.0,NaN,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5850832,558912989,02/18/2017,00:00:00,02/18/2017,00:20:00,06/09/2017,104,RAPE,157.0,RAPE 1,...,115.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4837498,729580311,06/29/2006,00:00:00,06/29/2006,01:50:00,06/29/2006,104,RAPE,153.0,RAPE 3,...,94.0,NaN,STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5663688,498470037,10/25/2017,00:00:00,NaN,NaN,10/25/2017,104,RAPE,153.0,RAPE 3,...,72.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1205883,815932924,07/05/2013,00:00:00,NaN,NaN,07/16/2013,104,RAPE,157.0,RAPE 1,...,75.0,INSIDE,RESIDENCE - PUBLIC HOUSING,NaN,PINK,NaN,NaN,NaN,NaN,NaN
5847891,879729269,06/11/2017,00:00:00,06/11/2017,05:30:00,06/11/2017,104,RAPE,157.0,RAPE 1,...,71.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
513711,724926698,08/01/2014,00:00:00,NaN,NaN,12/01/2014,104,RAPE,155.0,RAPE 2,...,40.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1216093,692749396,01/01/2005,00:00:00,06/26/2013,21:00:00,07/09/2013,104,RAPE,157.0,RAPE 1,...,113.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
513596,690143250,11/21/2014,00:00:00,11/21/2014,23:59:00,12/01/2014,104,RAPE,155.0,RAPE 2,...,47.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4813959,494081214,06/09/2006,00:00:00,06/09/2006,17:00:00,07/15/2006,104,RAPE,155.0,RAPE 2,...,67.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1221138,722597337,07/05/2013,00:00:00,07/05/2013,03:00:00,07/05/2013,104,RAPE,157.0,RAPE 1,...,42.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4792372,580633722,12/12/2003,00:00:00,NaN,NaN,07/29/2006,104,RAPE,157.0,RAPE 1,...,83.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5844361,691889078,02/01/2017,00:00:00,02/28/2017,23:59:00,06/14/2017,104,RAPE,157.0,RAPE 1,...,71.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1230855,597374927,06/28/2013,00:00:00,06/28/2013,12:04:00,06/28/2013,104,RAPE,157.0,RAPE 1,...,109.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2260546,893886899,01/01/1998,00:00:00,NaN,NaN,06/06/2011,104,RAPE,157.0,RAPE 1,...,75.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df_rape.sort_values(by='CMPLNT_TO_TM', ascending=False)

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,RPT_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,...,ADDR_PCT_CD,LOC_OF_OCCUR_DESC,PREM_TYP_DESC,PARKS_NM,HADEVELOPT,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon
3841350,618252524,05/24/2006,09:00:00,01/01/2008,23:59:59,05/07/2008,104,RAPE,155.0,RAPE 2,...,48.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3439084,763217678,09/01/2008,23:59:59,01/12/2009,23:59:59,02/11/2009,104,RAPE,153.0,RAPE 3,...,120.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3440507,203276462,01/10/2009,00:01:00,01/10/2009,23:59:59,02/10/2009,104,RAPE,153.0,RAPE 3,...,115.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3656480,606699261,01/01/2005,15:00:00,04/30/2008,23:59:59,09/07/2008,104,RAPE,157.0,RAPE 1,...,50.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4201880,155768460,07/07/2007,20:00:00,07/08/2007,23:59:59,09/02/2007,104,RAPE,155.0,RAPE 2,...,47.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3441876,965083518,11/01/2008,23:59:59,11/15/2008,23:59:59,02/09/2009,104,RAPE,157.0,RAPE 1,...,105.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4046403,576727230,12/13/2007,18:00:00,12/14/2007,23:59:59,12/14/2007,104,RAPE,153.0,RAPE 3,...,83.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4313564,570578651,07/01/2006,10:00:00,04/01/2007,23:59:59,06/21/2007,104,RAPE,153.0,RAPE 3,...,122.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3445603,597213125,05/01/2008,00:01:00,12/20/2008,23:59:59,02/06/2009,104,RAPE,153.0,RAPE 3,...,23.0,INSIDE,RESIDENCE - PUBLIC HOUSING,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3887411,375676496,06/01/2003,15:00:00,06/30/2004,23:59:59,04/05/2008,104,RAPE,157.0,RAPE 1,...,44.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3780568,228835328,05/01/2008,19:00:00,05/31/2008,23:59:59,06/17/2008,104,RAPE,157.0,RAPE 1,...,48.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3474079,506025924,01/01/2002,00:01:00,11/10/2007,23:59:59,01/15/2009,104,RAPE,157.0,RAPE 1,...,24.0,INSIDE,RESIDENCE - PUBLIC HOUSING,NaN,DOUGLASS,NaN,NaN,NaN,NaN,NaN
3627526,558928215,06/01/2002,00:01:00,06/01/2004,23:59:59,09/26/2008,104,RAPE,155.0,RAPE 2,...,110.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3475521,236062851,06/20/2008,00:01:00,06/20/2008,23:59:59,01/14/2009,104,RAPE,153.0,RAPE 3,...,101.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3627519,635585222,12/01/2006,08:00:00,08/30/2008,23:59:59,09/26/2008,104,RAPE,157.0,RAPE 1,...,43.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4175559,539326206,08/25/2007,20:00:00,08/31/2007,23:59:59,09/19/2007,104,RAPE,153.0,RAPE 3,...,115.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3627518,923962986,12/01/2006,08:00:00,08/30/2008,23:59:59,09/26/2008,104,RAPE,157.0,RAPE 1,...,43.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4028031,636302228,07/01/2007,00:01:00,07/01/2007,23:59:59,12/28/2007,104,RAPE,153.0,RAPE 3,...,100.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3253528,681404145,02/15/2009,00:05:00,04/30/2009,23:59:59,05/12/2009,104,RAPE,153.0,RAPE 3,...,42.0,INSIDE,RESIDENCE - PUBLIC HOUSING,NaN,FOREST,NaN,NaN,NaN,NaN,NaN
3627516,962107012,12/01/2006,08:00:00,08/30/2008,23:59:59,09/26/2008,104,RAPE,157.0,RAPE 1,...,43.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4009539,890403625,12/25/2007,09:00:00,12/25/2007,23:59:59,01/10/2008,104,RAPE,157.0,RAPE 1,...,113.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3364162,104869755,01/01/2003,00:01:00,12/31/2004,23:59:59,04/06/2009,104,RAPE,157.0,RAPE 1,...,67.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3365325,435656502,02/23/2008,23:20:00,02/23/2008,23:59:59,04/05/2009,104,RAPE,157.0,RAPE 1,...,19.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3925434,605287473,01/14/2008,19:30:00,01/14/2008,23:59:59,03/10/2008,104,RAPE,157.0,RAPE 1,...,70.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3924004,575378260,02/15/2005,00:01:00,04/15/2005,23:59:59,03/11/2008,104,RAPE,155.0,RAPE 2,...,120.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3317867,979303907,02/21/2009,11:00:00,04/27/2009,23:59:59,05/09/2009,104,RAPE,153.0,RAPE 3,...,105.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3315293,464282843,01/01/2006,09:00:00,05/06/2009,23:59:59,05/11/2009,104,RAPE,155.0,RAPE 2,...,18.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3747753,756854942,05/03/2008,08:00:00,05/10/2008,23:59:59,07/09/2008,104,RAPE,153.0,RAPE 3,...,44.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3680201,984301010,02/15/2008,23:00:00,07/14/2008,23:59:59,08/22/2008,104,RAPE,155.0,RAPE 2,...,73.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3972010,967821761,12/21/2007,00:01:00,01/15/2008,23:59:59,02/05/2008,104,RAPE,157.0,RAPE 1,...,67.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5985259,271216562,02/21/2017,15:30:00,NaN,NaN,02/22/2017,104,RAPE,157.0,RAPE 1,...,18.0,INSIDE,STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5986509,406701586,02/19/2017,08:00:00,NaN,NaN,02/21/2017,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,103.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5986593,864625264,02/16/2017,13:00:00,NaN,NaN,02/21/2017,104,RAPE,157.0,RAPE 1,...,42.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5987867,686605026,12/30/2016,05:30:00,NaN,NaN,02/20/2017,104,RAPE,157.0,RAPE 1,...,77.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5988470,103530835,02/19/2017,04:40:00,NaN,NaN,02/19/2017,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,13.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5988623,939899738,02/19/2017,01:10:00,NaN,NaN,02/19/2017,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,43.0,NaN,STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5989725,133266438,02/18/2017,01:30:00,NaN,NaN,02/18/2017,104,RAPE,157.0,RAPE 1,...,13.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5992591,158991443,09/01/2016,00:01:00,NaN,NaN,02/16/2017,104,RAPE,157.0,RAPE 1,...,108.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6000607,816224620,02/08/2017,16:00:00,NaN,NaN,02/08/2017,104,RAPE,157.0,RAPE 1,...,121.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6001460,943681079,02/04/2017,17:45:00,NaN,NaN,02/08/2017,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,73.0,INSIDE,HOTEL/MOTEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6002208,556276576,02/07/2017,12:00:00,NaN,NaN,02/07/2017,104,RAPE,157.0,RAPE 1,...,41.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6002665,824731362,02/06/2017,07:00:00,NaN,NaN,02/07/2017,104,RAPE,157.0,RAPE 1,...,22.0,NaN,PARK/PLAYGROUND,CENTRAL PARK,NaN,NaN,NaN,NaN,NaN,NaN
6010192,454899457,01/28/2017,02:00:00,NaN,NaN,02/01/2017,104,RAPE,157.0,RAPE 1,...,1.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6014993,482125095,01/26/2017,11:30:00,NaN,NaN,01/28/2017,104,RAPE,157.0,RAPE 1,...,68.0,NaN,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6017877,111079578,05/01/2016,12:00:00,NaN,NaN,01/26/2017,104,RAPE,153.0,RAPE 3,...,10.0,INSIDE,RESIDENCE - PUBLIC HOUSING,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6020384,616047446,01/17/2017,08:00:00,NaN,NaN,01/24/2017,104,RAPE,157.0,RAPE 1,...,7.0,INSIDE,RESIDENCE - PUBLIC HOUSING,NaN,RUTGERS,NaN,NaN,NaN,NaN,NaN
6020532,214593954,06/15/2016,21:00:00,NaN,NaN,01/24/2017,104,RAPE,157.0,RAPE 1,...,75.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6024561,312161086,01/20/2017,18:00:00,NaN,NaN,01/20/2017,104,RAPE,153.0,RAPE 3,...,47.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6026309,290195919,01/19/2017,11:10:00,NaN,NaN,01/19/2017,104,RAPE,157.0,RAPE 1,...,69.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6030380,463333341,01/16/2017,10:00:00,NaN,NaN,01/16/2017,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,73.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6033078,328625482,01/10/2017,02:00:00,NaN,NaN,01/14/2017,104,RAPE,157.0,RAPE 1,...,110.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6033649,434992579,01/13/2017,13:00:00,NaN,NaN,01/13/2017,104,RAPE,157.0,RAPE 1,...,43.0,INSIDE,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6034122,412823496,01/12/2017,21:00:00,NaN,NaN,01/13/2017,104,RAPE,157.0,RAPE 1,...,70.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6037243,677605048,09/12/2016,19:00:00,NaN,NaN,01/11/2017,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,114.0,INSIDE,RESIDENCE - PUBLIC HOUSING,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6038416,597920059,12/19/2016,00:30:00,NaN,NaN,01/10/2017,104,RAPE,157.0,RAPE 1,...,1.0,INSIDE,HOTEL/MOTEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6039315,261112645,01/06/2017,13:00:00,NaN,NaN,01/09/2017,104,RAPE,157.0,RAPE 1,...,23.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6040425,926840989,01/07/2017,21:00:00,NaN,NaN,01/07/2017,104,RAPE,157.0,RAPE 1,...,44.0,NaN,BRIDGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6042022,316742108,01/06/2017,00:15:00,NaN,NaN,01/06/2017,104,RAPE,157.0,RAPE 1,...,50.0,OPPOSITE OF,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6042481,771559023,01/06/2016,17:30:00,NaN,NaN,01/06/2017,104,RAPE,157.0,RAPE 1,...,14.0,FRONT OF,CHURCH,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6046089,485703034,01/02/2017,19:30:00,NaN,NaN,01/03/2017,104,RAPE,157.0,RAPE 1,...,32.0,INSIDE,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# Get rid of troublesome '1016' date value
format_check = df_rape.CMPLNT_FR_DT.str.extract('^(\d{2})/(\d{2})/(\d{4})')

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)

In [25]:
# The '1016' value is troublesome

In [26]:
format_check[2].unique()

array(['2015', '2009', '2012', '2008', '2014', '2006', '2013', '2010',
       '2002', '1993', '2011', '2007', '2003', '2000', '2005', '2004',
       '2001', '1999', '1975', '1996', '1997', '1992', '1998', '1990',
       '1994', '1988', '1995', '1989', '1978', '1991', '2016', '1984',
       '1980', '1986', '1016', '1983', '2017', '1973', '1968', '1967',
       '1976', '1981', '1987', '1977'], dtype=object)

In [27]:
df_rape['CMPLNT_FR_DT'] = df_rape['CMPLNT_FR_DT'].str.replace('1016','2016')

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [28]:
df_rape.loc[df_rape['CMPLNT_FR_DT'].str.contains('1016')]

Empty DataFrame
Columns: [CMPLNT_NUM, CMPLNT_FR_DT, CMPLNT_FR_TM, CMPLNT_TO_DT, CMPLNT_TO_TM, RPT_DT, KY_CD, OFNS_DESC, PD_CD, PD_DESC, CRM_ATPT_CPTD_CD, LAW_CAT_CD, JURIS_DESC, BORO_NM, ADDR_PCT_CD, LOC_OF_OCCUR_DESC, PREM_TYP_DESC, PARKS_NM, HADEVELOPT, X_COORD_CD, Y_COORD_CD, Latitude, Longitude, Lat_Lon]
Index: []

[0 rows x 24 columns]

# Creation of datetime column

In [29]:
# Fix up date columns

In [31]:
# Fix up time columns, create series for them

In [35]:
print(type(CMPLNT_FR_TM_series[21]), type(CMPLNT_TO_TM_series[21]))

<class 'pandas._libs.tslib.Timestamp'> <class 'pandas._libs.tslib.Timestamp'>

In [37]:
CMPLNT_datetime_series_FR = df_rape['CMPLNT_FR_DT'] + ' ' + df_rape['CMPLNT_FR_TM']

In [38]:
CMPLNT_datetime_series_TO = df_rape['CMPLNT_TO_DT'] + ' ' + df_rape['CMPLNT_TO_TM']

In [39]:
print(type(CMPLNT_datetime_series_FR[21]), type(CMPLNT_datetime_series_TO[21]))

<class 'str'> <class 'str'>

In [40]:
CMPLNT_datetime_series_FR

21         04/06/2015 12:00:00
252        12/01/2009 10:00:00
821        12/30/2015 18:00:00
1079       08/01/2015 00:01:00
1754       12/30/2015 03:04:00
2086       12/28/2015 18:00:00
2269       11/27/2015 20:00:00
2716       12/29/2015 15:30:00
3199       12/28/2015 20:00:00
3346       12/26/2015 02:30:00
4024       12/27/2015 21:30:00
4281       12/28/2015 02:40:00
5617       12/27/2015 01:00:00
5674       12/26/2015 23:30:00
5686       12/26/2015 23:00:00
5879       12/25/2015 06:00:00
5885       12/25/2015 02:00:00
5991       11/03/2015 12:00:00
6015       07/20/2015 12:00:00
6576       12/26/2015 09:25:00
6634       12/26/2015 05:00:00
7601       12/25/2015 04:00:00
7602       12/25/2015 02:30:00
7853       12/24/2015 17:30:00
7874       10/12/2015 00:01:00
8118       12/24/2015 18:00:00
8565       12/24/2015 03:25:00
9134       11/19/2015 23:00:00
10186      10/01/2015 12:00:00
10201      06/03/2015 01:00:00
                  ...
6040310    01/01/2017 00:01:00
6040425    01/07/2017 21:00:00
6040838    01/07/2017 04:00:00
6041810    01/06/2017 10:00:00
6042022    01/06/2017 00:15:00
6042246    01/04/2017 13:00:00
6042481    01/06/2016 17:30:00
6043297    01/05/2017 01:10:00
6043679    12/28/2016 08:00:00
6043850    08/01/2015 00:01:00
6043853    07/07/2013 08:00:00
6044850    01/03/2017 15:30:00
6045256    12/14/2014 18:00:00
6045257    07/28/2013 02:00:00
6045948    01/03/2017 03:00:00
6045964    01/03/2017 02:15:00
6045989    01/03/2017 01:00:00
6046089    01/02/2017 19:30:00
6046316    12/28/2016 02:00:00
6046505    06/01/2016 00:00:00
6047219    01/01/2017 23:35:00
6047380    01/01/2017 02:30:00
6047433    12/31/2016 00:20:00
6047599    10/26/2016 09:00:00
6047627    09/01/2011 00:00:00
6048179    01/01/2017 05:00:00
6048486    01/01/2017 01:00:00
6048513    01/01/2017 00:30:00
6048726    12/29/2016 23:00:00
6048795    10/01/2012 00:01:00
Length: 16673, dtype: object

In [ ]:
CMPLNT_datetime_series_TO

In [ ]:
# Timestamps for each of the columns

In [ ]:
pd.to_datetime(CMPLNT_datetime_series_FR, infer_datetime_format=True)

In [ ]:
pd.to_datetime(CMPLNT_datetime_series_TO, infer_datetime_format=True)

In [ ]:
# OK, looks good, a series of Timestamps

In [ ]:
type(pd.to_datetime(CMPLNT_datetime_series_FR, infer_datetime_format=True)[21])

In [41]:
type(CMPLNT_datetime_series_FR[21])

str

In [42]:
CMPLNT_datetime_series_TO

21         04/10/2015 18:00:00
252        01/01/2010 10:00:00
821        12/30/2015 23:00:00
1079       12/30/2015 22:25:00
1754       12/30/2015 05:19:00
2086       12/28/2015 19:00:00
2269                       NaN
2716                       NaN
3199       12/28/2015 20:30:00
3346       12/26/2015 06:00:00
4024       12/27/2015 22:00:00
4281       12/28/2015 03:00:00
5617       12/27/2015 01:20:00
5674                       NaN
5686       12/27/2015 06:40:00
5879       12/25/2015 09:00:00
5885       12/25/2015 03:00:00
5991       11/03/2015 13:00:00
6015                       NaN
6576       12/26/2015 09:30:00
6634                       NaN
7601       12/25/2015 04:30:00
7602       12/25/2015 06:00:00
7853       12/25/2015 07:30:00
7874       10/12/2015 23:59:00
8118       12/24/2015 18:30:00
8565       12/24/2015 03:40:00
9134       11/19/2015 23:59:00
10186      10/31/2015 12:00:00
10201      06/03/2015 02:00:00
                  ...
6040310    01/05/2017 23:59:00
6040425                    NaN
6040838    01/07/2017 05:45:00
6041810    01/06/2017 10:20:00
6042022                    NaN
6042246    01/04/2017 15:00:00
6042481                    NaN
6043297    01/05/2017 01:30:00
6043679    12/28/2016 08:30:00
6043850    08/31/2015 23:59:00
6043853    07/07/2014 08:00:00
6044850    01/03/2017 16:15:00
6045256    01/09/2015 15:00:00
6045257    07/28/2013 02:30:00
6045948    01/03/2017 03:30:00
6045964    01/03/2017 03:30:00
6045989    01/03/2017 01:30:00
6046089                    NaN
6046316    12/28/2016 02:30:00
6046505    07/30/2016 00:00:00
6047219    01/01/2017 23:54:00
6047380    01/01/2017 12:30:00
6047433    12/31/2016 00:20:00
6047599    10/26/2016 15:00:00
6047627    11/01/2012 00:00:00
6048179    01/01/2017 06:00:00
6048486    01/01/2017 02:00:00
6048513    01/01/2017 00:55:00
6048726    12/30/2016 10:00:00
6048795    10/01/2012 00:01:00
Length: 16673, dtype: object

In [43]:
type(pd.to_datetime(CMPLNT_datetime_series_TO, infer_datetime_format=True)[21])

pandas._libs.tslib.Timestamp

In [44]:
# Successfully added a column with an incorrect date
# Try .loc with the proper to_datetime application?

df_rape['CMPLNT_FR_DATETIME'] = CMPLNT_datetime_series_FR
# df_rape = df_rape.assign(CMPLNT_FR_TM_series)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [45]:
df_rape['CMPLNT_TO_DATETIME'] = CMPLNT_datetime_series_TO

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [46]:
df_rape

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,RPT_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,...,PREM_TYP_DESC,PARKS_NM,HADEVELOPT,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon,CMPLNT_FR_DATETIME,CMPLNT_TO_DATETIME
21,340513307,04/06/2015,12:00:00,04/10/2015,18:00:00,12/21/2015,104,RAPE,155.0,RAPE 2,...,OTHER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/06/2015 12:00:00,04/10/2015 18:00:00
252,198273659,12/01/2009,10:00:00,01/01/2010,10:00:00,12/07/2015,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/01/2009 10:00:00,01/01/2010 10:00:00
821,591506102,12/30/2015,18:00:00,12/30/2015,23:00:00,12/31/2015,104,RAPE,157.0,RAPE 1,...,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/30/2015 18:00:00,12/30/2015 23:00:00
1079,283109223,08/01/2015,00:01:00,12/30/2015,22:25:00,12/31/2015,104,RAPE,153.0,RAPE 3,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,08/01/2015 00:01:00,12/30/2015 22:25:00
1754,361697946,12/30/2015,03:04:00,12/30/2015,05:19:00,12/30/2015,104,RAPE,157.0,RAPE 1,...,HOTEL/MOTEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/30/2015 03:04:00,12/30/2015 05:19:00
2086,449252466,12/28/2015,18:00:00,12/28/2015,19:00:00,12/30/2015,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/28/2015 18:00:00,12/28/2015 19:00:00
2269,841076951,11/27/2015,20:00:00,NaN,NaN,12/30/2015,104,RAPE,153.0,RAPE 3,...,RESIDENCE - PUBLIC HOUSING,NaN,MANHATTANVILLE,NaN,NaN,NaN,NaN,NaN,11/27/2015 20:00:00,NaN
2716,462568423,12/29/2015,15:30:00,NaN,NaN,12/29/2015,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/29/2015 15:30:00,NaN
3199,632341905,12/28/2015,20:00:00,12/28/2015,20:30:00,12/29/2015,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/28/2015 20:00:00,12/28/2015 20:30:00
3346,706551270,12/26/2015,02:30:00,12/26/2015,06:00:00,12/29/2015,104,RAPE,155.0,RAPE 2,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/26/2015 02:30:00,12/26/2015 06:00:00
4024,994921451,12/27/2015,21:30:00,12/27/2015,22:00:00,12/28/2015,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/27/2015 21:30:00,12/27/2015 22:00:00
4281,646084375,12/28/2015,02:40:00,12/28/2015,03:00:00,12/28/2015,104,RAPE,153.0,RAPE 3,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/28/2015 02:40:00,12/28/2015 03:00:00
5617,139481182,12/27/2015,01:00:00,12/27/2015,01:20:00,12/27/2015,104,RAPE,157.0,RAPE 1,...,STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/27/2015 01:00:00,12/27/2015 01:20:00
5674,621813268,12/26/2015,23:30:00,NaN,NaN,12/27/2015,104,RAPE,157.0,RAPE 1,...,HOSPITAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/26/2015 23:30:00,NaN
5686,181372401,12/26/2015,23:00:00,12/27/2015,06:40:00,12/27/2015,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/26/2015 23:00:00,12/27/2015 06:40:00
5879,438169439,12/25/2015,06:00:00,12/25/2015,09:00:00,12/27/2015,104,RAPE,157.0,RAPE 1,...,HOTEL/MOTEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/25/2015 06:00:00,12/25/2015 09:00:00
5885,472968111,12/25/2015,02:00:00,12/25/2015,03:00:00,12/27/2015,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/25/2015 02:00:00,12/25/2015 03:00:00
5991,448202906,11/03/2015,12:00:00,11/03/2015,13:00:00,12/27/2015,104,RAPE,155.0,RAPE 2,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11/03/2015 12:00:00,11/03/2015 13:00:00
6015,628688223,07/20/2015,12:00:00,NaN,NaN,12/27/2015,104,RAPE,153.0,RAPE 3,...,HOTEL/MOTEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/20/2015 12:00:00,NaN
6576,651135996,12/26/2015,09:25:00,12/26/2015,09:30:00,12/26/2015,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/26/2015 09:25:00,12/26/2015 09:30:00
6634,279632944,12/26/2015,05:00:00,NaN,NaN,12/26/2015,104,RAPE,157.0,RAPE 1,...,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/26/2015 05:00:00,NaN
7601,313805073,12/25/2015,04:00:00,12/25/2015,04:30:00,12/25/2015,104,RAPE,157.0,RAPE 1,...,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/25/2015 04:00:00,12/25/2015 04:30:00
7602,488490546,12/25/2015,02:30:00,12/25/2015,06:00:00,12/25/2015,104,RAPE,157.0,RAPE 1,...,PARK/PLAYGROUND,FORT GREENE PARK,NaN,NaN,NaN,NaN,NaN,NaN,12/25/2015 02:30:00,12/25/2015 06:00:00
7853,582000545,12/24/2015,17:30:00,12/25/2015,07:30:00,12/25/2015,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/24/2015 17:30:00,12/25/2015 07:30:00
7874,604012954,10/12/2015,00:01:00,10/12/2015,23:59:00,12/19/2015,104,RAPE,155.0,RAPE 2,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10/12/2015 00:01:00,10/12/2015 23:59:00
8118,546749201,12/24/2015,18:00:00,12/24/2015,18:30:00,12/24/2015,104,RAPE,157.0,RAPE 1,...,STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/24/2015 18:00:00,12/24/2015 18:30:00
8565,543298286,12/24/2015,03:25:00,12/24/2015,03:40:00,12/24/2015,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/24/2015 03:25:00,12/24/2015 03:40:00
9134,177516683,11/19/2015,23:00:00,11/19/2015,23:59:00,12/16/2015,104,RAPE,157.0,RAPE 1,...,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11/19/2015 23:00:00,11/19/2015 23:59:00
10186,509053834,10/01/2015,12:00:00,10/31/2015,12:00:00,12/23/2015,104,RAPE,153.0,RAPE 3,...,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10/01/2015 12:00:00,10/31/2015 12:00:00
10201,550344851,06/03/2015,01:00:00,06/03/2015,02:00:00,12/23/2015,104,RAPE,153.0,RAPE 3,...,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06/03/2015 01:00:00,06/03/2015 02:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6040310,972316045,01/01/2017,00:01:00,01/05/2017,23:59:00,01/08/2017,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/01/2017 00:01:00,01/05/2017 23:59:00
6040425,926840989,01/07/2017,21:00:00,NaN,NaN,01/07/2017,104,RAPE,157.0,RAPE 1,...,BRIDGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/07/2017 21:00:00,NaN
6040838,167132012,01/07/2017,04:00:00,01/07/2017,05:45:00,01/07/2017,104,RAPE,157.0,RAPE 1,...,STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/07/2017 04:00:00,01/07/2017 05:45:00
6041810,559562266,01/06/2017,10:00:00,01/06/2017,10:20:00,01/06/2017,104,RAPE,157.0,RAPE 1,...,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/06/2017 10:00:00,01/06/2017 10:20:00
6042022,316742108,01/06/2017,00:15:00,NaN,NaN,01/06/2017,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/06/2017 00:15:00,NaN
6042246,940269397,01/04/2017,13:00:00,01/04/2017,15:00:00,01/06/2017,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/04/2017 13:00:00,01/04/2017 15:00:00
6042481,771559023,01/06/2016,17:30:00,NaN,NaN,01/06/2017,104,RAPE,157.0,RAPE 1,...,CHURCH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/06/2016 17:30:00,NaN
6043297,702852795,01/05/2017,01:10:00,01/05/2017,01:30:00,01/05/2017,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/05/2017 01:10:00,01/05/2017 01:30:00
6043679,701108331,12/28/2016,08:00:00,12/28/2016,08:30:00,01/05/2017,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/28/2016 08:00:00,12/28/2016 08:30:00
6043850,154459729,08/01/2015,00:01:00,08/31/2015,23:59:00,01/05/2017,104,RAPE,153.0,RAPE 3,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,08/01/2015 00:01:00,08/31/2015 23:59:00
6043853,323823903,07/07/2013,08:00:00,07/07/2014,08:00:00,01/05/2017,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/07/2013 08:00:00,07/07/2014 08:00:00
6044850,675886498,01/03/2017,15:30:00,01/03/2017,16:15:00,01/04/2017,104,RAPE,157.0,RAPE 1,...,RESIDENCE - PUBLIC HOUSING,NaN,ADAMS,NaN,NaN,NaN,NaN,NaN,01/03/2017 15:30:00,01/03/2017 16:15:00
6045256,367643547,12/14/2014,18:00:00,01/09/2015,15:00:00,01/04/2017,104,RAPE,157.0,RAPE 1,...,HOSPITAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/14/2014 18:00:00,01/09/2015 15:00:00
6045257,632841445,07/28/2013,02:00:00,07/28/2013,02:30:00,01/04/2017,104,RAPE,157.0,RAPE 1,...,HOTEL/MOTEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/28/2013 02:00:00,07/28/2013 02:30:00
6045948,552188042,01/03/2017,03:00:00,01/03/2017,03:30:00,01/03/2017,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/03/2017 03:00:00,01/03/2017 03:30:00
6045964,112199910,01/03/2017,02:15:00,01/03/2017,03:30:00,01/03/2017,104,RAPE,153.0,RAPE 3,...,HOTEL/MOTEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/03/2017 02:15:00,01/03/2017 03:30:00
6045989,621378019,01/03/2017,01:00:00,01/03/2017,01:30:00,01/03/2017,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/03/2017 01:00:00,01/03/2017 01:30:00
6046089,485703034,01/02/2017,19:30:00,NaN,NaN,01/03/2017,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/02/2017 19:30:00,NaN
6046316,839785044,12/28/2016,02:00:00,12/28/2016,02:30:00,01/03/2017,104,RAPE,153.0,RAPE 3,...,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/28/2016 02:00:00,12/28/2016 02:30:00
6046505,516701965,06/01/2016,00:00:00,07/30/2016,00:00:00,01/03/2017,104,RAPE,155.0,RAPE 2,...,RESIDENCE-HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06/01/2016 00:00:00,07/30/2016 00:00:00
6047219,354182596,01/01/2017,23:35:00,01/01/2017,23:54:00,01/02/2017,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/01/2017 23:35:00,01/01/2017 23:54:00
6047380,470690353,01/01/2017,02:30:00,01/01/2017,12:30:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/01/2017 02:30:00,01/01/2017 12:30:00
6047433,342860150,12/31/2016,00:20:00,12/31/2016,00:20:00,01/02/2017,104,RAPE,155.0,RAPE 2,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/31/2016 00:20:00,12/31/2016 00:20:00
6047599,344368026,10/26/2016,09:00:00,10/26/2016,15:00:00,01/02/2017,104,RAPE,155.0,RAPE 2,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10/26/2016 09:00:00,10/26/2016 15:00:00
6047627,875232609,09/01/2011,00:00:00,11/01/2012,00:00:00,01/02/2017,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09/01/2011 00:00:00,11/01/2012 00:00:00
6048179,108254204,01/01/2017,05:00:00,01/01/2017,06:00:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/01/2017 05:00:00,01/01/2017 06:00:00
6048486,895568117,01/01/2017,01:00:00,01/01/2017,02:00:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,RESIDENCE - APT. HOUSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/01/2017 01:00:00,01/01/2017 02:00:00
6048513,629297118,01/01/2017,00:30:00,01/01/2017,00:55:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,BAR/NIGHT CLUB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/01/2017 00:30:00,01/01/2017 00:55:00
6048726,376969658,12/29/2016,23:00:00,12/30/2016,10:00:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,HOTEL/MOTEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/29/2016 23:00:00,12/30/2016 10:00:00
6048795,329336049,10/01/2012,00:01:00,10/01/2012,00:01:00,01/01/2017,104,RAPE,153.0,RAPE 3,...,RESIDENCE - PUBLIC HOUSING,NaN,DOUGLASS,NaN,NaN,NaN,NaN,NaN,10/01/2012 00:01:00,10/01/2012 00:01:00

In [47]:
# Wait, what? Strings?

In [48]:
type(df_rape['CMPLNT_FR_DATETIME'][21])

str

In [49]:
type(df_rape['CMPLNT_TO_DATETIME'][21])

str

In [50]:
df_rape.dtypes

CMPLNT_NUM              int64
CMPLNT_FR_DT           object
CMPLNT_FR_TM           object
CMPLNT_TO_DT           object
CMPLNT_TO_TM           object
RPT_DT                 object
KY_CD                   int64
OFNS_DESC              object
PD_CD                 float64
PD_DESC                object
CRM_ATPT_CPTD_CD       object
LAW_CAT_CD             object
JURIS_DESC             object
BORO_NM                object
ADDR_PCT_CD           float64
LOC_OF_OCCUR_DESC      object
PREM_TYP_DESC          object
PARKS_NM               object
HADEVELOPT             object
X_COORD_CD            float64
Y_COORD_CD            float64
Latitude              float64
Longitude             float64
Lat_Lon                object
CMPLNT_FR_DATETIME     object
CMPLNT_TO_DATETIME     object
dtype: object

In [51]:
df_rape['CMPLNT_FR_DATETIME'] = pd.to_datetime(df_rape['CMPLNT_FR_DATETIME'], infer_datetime_format=True)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [52]:
type(pd.to_datetime(df_rape['CMPLNT_FR_DATETIME'], infer_datetime_format=True)[21])

pandas._libs.tslib.Timestamp

In [108]:
df_rape['RPT_DT'] = pd.to_datetime(df_rape['RPT_DT'], infer_datetime_format=True)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [53]:
df_rape['CMPLNT_TO_DATETIME'] = pd.to_datetime(df_rape['CMPLNT_TO_DATETIME'], infer_datetime_format=True)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [54]:
type(df_rape['CMPLNT_FR_DATETIME'][21])

pandas._libs.tslib.Timestamp

In [55]:
# Need to .loc the Timestamp types
df_rape['CRIME_DURATION'] = df_rape['CMPLNT_TO_DATETIME'] - df_rape['CMPLNT_FR_DATETIME']

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [56]:

df_rape

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,RPT_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,...,PARKS_NM,HADEVELOPT,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon,CMPLNT_FR_DATETIME,CMPLNT_TO_DATETIME,CRIME_DURATION
21,340513307,04/06/2015,12:00:00,04/10/2015,18:00:00,12/21/2015,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-04-06 12:00:00,2015-04-10 18:00:00,4 days 06:00:00
252,198273659,12/01/2009,10:00:00,01/01/2010,10:00:00,12/07/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-12-01 10:00:00,2010-01-01 10:00:00,31 days 00:00:00
821,591506102,12/30/2015,18:00:00,12/30/2015,23:00:00,12/31/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-30 18:00:00,2015-12-30 23:00:00,0 days 05:00:00
1079,283109223,08/01/2015,00:01:00,12/30/2015,22:25:00,12/31/2015,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-08-01 00:01:00,2015-12-30 22:25:00,151 days 22:24:00
1754,361697946,12/30/2015,03:04:00,12/30/2015,05:19:00,12/30/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-30 03:04:00,2015-12-30 05:19:00,0 days 02:15:00
2086,449252466,12/28/2015,18:00:00,12/28/2015,19:00:00,12/30/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-28 18:00:00,2015-12-28 19:00:00,0 days 01:00:00
2269,841076951,11/27/2015,20:00:00,NaN,NaN,12/30/2015,104,RAPE,153.0,RAPE 3,...,NaN,MANHATTANVILLE,NaN,NaN,NaN,NaN,NaN,2015-11-27 20:00:00,NaT,NaT
2716,462568423,12/29/2015,15:30:00,NaN,NaN,12/29/2015,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-29 15:30:00,NaT,NaT
3199,632341905,12/28/2015,20:00:00,12/28/2015,20:30:00,12/29/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-28 20:00:00,2015-12-28 20:30:00,0 days 00:30:00
3346,706551270,12/26/2015,02:30:00,12/26/2015,06:00:00,12/29/2015,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-26 02:30:00,2015-12-26 06:00:00,0 days 03:30:00
4024,994921451,12/27/2015,21:30:00,12/27/2015,22:00:00,12/28/2015,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-27 21:30:00,2015-12-27 22:00:00,0 days 00:30:00
4281,646084375,12/28/2015,02:40:00,12/28/2015,03:00:00,12/28/2015,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-28 02:40:00,2015-12-28 03:00:00,0 days 00:20:00
5617,139481182,12/27/2015,01:00:00,12/27/2015,01:20:00,12/27/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-27 01:00:00,2015-12-27 01:20:00,0 days 00:20:00
5674,621813268,12/26/2015,23:30:00,NaN,NaN,12/27/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-26 23:30:00,NaT,NaT
5686,181372401,12/26/2015,23:00:00,12/27/2015,06:40:00,12/27/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-26 23:00:00,2015-12-27 06:40:00,0 days 07:40:00
5879,438169439,12/25/2015,06:00:00,12/25/2015,09:00:00,12/27/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-25 06:00:00,2015-12-25 09:00:00,0 days 03:00:00
5885,472968111,12/25/2015,02:00:00,12/25/2015,03:00:00,12/27/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-25 02:00:00,2015-12-25 03:00:00,0 days 01:00:00
5991,448202906,11/03/2015,12:00:00,11/03/2015,13:00:00,12/27/2015,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-11-03 12:00:00,2015-11-03 13:00:00,0 days 01:00:00
6015,628688223,07/20/2015,12:00:00,NaN,NaN,12/27/2015,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-07-20 12:00:00,NaT,NaT
6576,651135996,12/26/2015,09:25:00,12/26/2015,09:30:00,12/26/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-26 09:25:00,2015-12-26 09:30:00,0 days 00:05:00
6634,279632944,12/26/2015,05:00:00,NaN,NaN,12/26/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-26 05:00:00,NaT,NaT
7601,313805073,12/25/2015,04:00:00,12/25/2015,04:30:00,12/25/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-25 04:00:00,2015-12-25 04:30:00,0 days 00:30:00
7602,488490546,12/25/2015,02:30:00,12/25/2015,06:00:00,12/25/2015,104,RAPE,157.0,RAPE 1,...,FORT GREENE PARK,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-25 02:30:00,2015-12-25 06:00:00,0 days 03:30:00
7853,582000545,12/24/2015,17:30:00,12/25/2015,07:30:00,12/25/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-24 17:30:00,2015-12-25 07:30:00,0 days 14:00:00
7874,604012954,10/12/2015,00:01:00,10/12/2015,23:59:00,12/19/2015,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-10-12 00:01:00,2015-10-12 23:59:00,0 days 23:58:00
8118,546749201,12/24/2015,18:00:00,12/24/2015,18:30:00,12/24/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-24 18:00:00,2015-12-24 18:30:00,0 days 00:30:00
8565,543298286,12/24/2015,03:25:00,12/24/2015,03:40:00,12/24/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-24 03:25:00,2015-12-24 03:40:00,0 days 00:15:00
9134,177516683,11/19/2015,23:00:00,11/19/2015,23:59:00,12/16/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-11-19 23:00:00,2015-11-19 23:59:00,0 days 00:59:00
10186,509053834,10/01/2015,12:00:00,10/31/2015,12:00:00,12/23/2015,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-10-01 12:00:00,2015-10-31 12:00:00,30 days 00:00:00
10201,550344851,06/03/2015,01:00:00,06/03/2015,02:00:00,12/23/2015,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-06-03 01:00:00,2015-06-03 02:00:00,0 days 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6040310,972316045,01/01/2017,00:01:00,01/05/2017,23:59:00,01/08/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-01 00:01:00,2017-01-05 23:59:00,4 days 23:58:00
6040425,926840989,01/07/2017,21:00:00,NaN,NaN,01/07/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-07 21:00:00,NaT,NaT
6040838,167132012,01/07/2017,04:00:00,01/07/2017,05:45:00,01/07/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-07 04:00:00,2017-01-07 05:45:00,0 days 01:45:00
6041810,559562266,01/06/2017,10:00:00,01/06/2017,10:20:00,01/06/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-06 10:00:00,2017-01-06 10:20:00,0 days 00:20:00
6042022,316742108,01/06/2017,00:15:00,NaN,NaN,01/06/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-06 00:15:00,NaT,NaT
6042246,940269397,01/04/2017,13:00:00,01/04/2017,15:00:00,01/06/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-04 13:00:00,2017-01-04 15:00:00,0 days 02:00:00
6042481,771559023,01/06/2016,17:30:00,NaN,NaN,01/06/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-06 17:30:00,NaT,NaT
6043297,702852795,01/05/2017,01:10:00,01/05/2017,01:30:00,01/05/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-05 01:10:00,2017-01-05 01:30:00,0 days 00:20:00
6043679,701108331,12/28/2016,08:00:00,12/28/2016,08:30:00,01/05/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-28 08:00:00,2016-12-28 08:30:00,0 days 00:30:00
6043850,154459729,08/01/2015,00:01:00,08/31/2015,23:59:00,01/05/2017,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-08-01 00:01:00,2015-08-31 23:59:00,30 days 23:58:00
6043853,323823903,07/07/2013,08:00:00,07/07/2014,08:00:00,01/05/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-07-07 08:00:00,2014-07-07 08:00:00,365 days 00:00:00
6044850,675886498,01/03/2017,15:30:00,01/03/2017,16:15:00,01/04/2017,104,RAPE,157.0,RAPE 1,...,NaN,ADAMS,NaN,NaN,NaN,NaN,NaN,2017-01-03 15:30:00,2017-01-03 16:15:00,0 days 00:45:00
6045256,367643547,12/14/2014,18:00:00,01/09/2015,15:00:00,01/04/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-14 18:00:00,2015-01-09 15:00:00,25 days 21:00:00
6045257,632841445,07/28/2013,02:00:00,07/28/2013,02:30:00,01/04/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-07-28 02:00:00,2013-07-28 02:30:00,0 days 00:30:00
6045948,552188042,01/03/2017,03:00:00,01/03/2017,03:30:00,01/03/2017,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-03 03:00:00,2017-01-03 03:30:00,0 days 00:30:00
6045964,112199910,01/03/2017,02:15:00,01/03/2017,03:30:00,01/03/2017,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-03 02:15:00,2017-01-03 03:30:00,0 days 01:15:00
6045989,621378019,01/03/2017,01:00:00,01/03/2017,01:30:00,01/03/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-03 01:00:00,2017-01-03 01:30:00,0 days 00:30:00
6046089,485703034,01/02/2017,19:30:00,NaN,NaN,01/03/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-02 19:30:00,NaT,NaT
6046316,839785044,12/28/2016,02:00:00,12/28/2016,02:30:00,01/03/2017,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-28 02:00:00,2016-12-28 02:30:00,0 days 00:30:00
6046505,516701965,06/01/2016,00:00:00,07/30/2016,00:00:00,01/03/2017,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-06-01 00:00:00,2016-07-30 00:00:00,59 days 00:00:00
6047219,354182596,01/01/2017,23:35:00,01/01/2017,23:54:00,01/02/2017,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-01 23:35:00,2017-01-01 23:54:00,0 days 00:19:00
6047380,470690353,01/01/2017,02:30:00,01/01/2017,12:30:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-01 02:30:00,2017-01-01 12:30:00,0 days 10:00:00
6047433,342860150,12/31/2016,00:20:00,12/31/2016,00:20:00,01/02/2017,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-31 00:20:00,2016-12-31 00:20:00,0 days 00:00:00
6047599,344368026,10/26/2016,09:00:00,10/26/2016,15:00:00,01/02/2017,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-10-26 09:00:00,2016-10-26 15:00:00,0 days 06:00:00
6047627,875232609,09/01/2011,00:00:00,11/01/2012,00:00:00,01/02/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-09-01 00:00:00,2012-11-01 00:00:00,427 days 00:00:00
6048179,108254204,01/01/2017,05:00:00,01/01/2017,06:00:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-01 05:00:00,2017-01-01 06:00:00,0 days 01:00:00
6048486,895568117,01/01/2017,01:00:00,01/01/2017,02:00:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-01 01:00:00,2017-01-01 02:00:00,0 days 01:00:00
6048513,629297118,01/01/2017,00:30:00,01/01/2017,00:55:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-01 00:30:00,2017-01-01 00:55:00,0 days 00:25:00
6048726,376969658,12/29/2016,23:00:00,12/30/2016,10:00:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-29 23:00:00,2016-12-30 10:00:00,0 days 11:00:00
6048795,329336049,10/01/2012,00:01:00,10/01/2012,00:01:00,01/01/2017,104,RAPE,153.0,RAPE 3,...,NaN,DOUGLASS,NaN,NaN,NaN,NaN,NaN,2012-10-01 00:01:00,2012-10-01 00:01:00,0 days 00:00:00

In [57]:
# Just some notes

data['hour'] = data['ts'].dt.hour
data['weekday'] = data['ts'].dt.weekday
data['weekday_name'] = data['ts'].dt.weekday_name

NameError: name 'data' is not defined

In [58]:
df_rape.dtypes

CMPLNT_NUM                      int64
CMPLNT_FR_DT                   object
CMPLNT_FR_TM                   object
CMPLNT_TO_DT                   object
CMPLNT_TO_TM                   object
RPT_DT                         object
KY_CD                           int64
OFNS_DESC                      object
PD_CD                         float64
PD_DESC                        object
CRM_ATPT_CPTD_CD               object
LAW_CAT_CD                     object
JURIS_DESC                     object
BORO_NM                        object
ADDR_PCT_CD                   float64
LOC_OF_OCCUR_DESC              object
PREM_TYP_DESC                  object
PARKS_NM                       object
HADEVELOPT                     object
X_COORD_CD                    float64
Y_COORD_CD                    float64
Latitude                      float64
Longitude                     float64
Lat_Lon                        object
CMPLNT_FR_DATETIME     datetime64[ns]
CMPLNT_TO_DATETIME     datetime64[ns]
CRIME_DURATION        timedelta64[ns]
dtype: object

In [61]:
df_rape['CRIME_DURATION']= df_rape['CMPLNT_TO_DATETIME'] - df_rape['CMPLNT_FR_DATETIME']

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [62]:
df_rape

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,RPT_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,...,PARKS_NM,HADEVELOPT,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon,CMPLNT_FR_DATETIME,CMPLNT_TO_DATETIME,CRIME_DURATION
21,340513307,04/06/2015,12:00:00,04/10/2015,18:00:00,12/21/2015,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-04-06 12:00:00,2015-04-10 18:00:00,4 days 06:00:00
252,198273659,12/01/2009,10:00:00,01/01/2010,10:00:00,12/07/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009-12-01 10:00:00,2010-01-01 10:00:00,31 days 00:00:00
821,591506102,12/30/2015,18:00:00,12/30/2015,23:00:00,12/31/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-30 18:00:00,2015-12-30 23:00:00,0 days 05:00:00
1079,283109223,08/01/2015,00:01:00,12/30/2015,22:25:00,12/31/2015,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-08-01 00:01:00,2015-12-30 22:25:00,151 days 22:24:00
1754,361697946,12/30/2015,03:04:00,12/30/2015,05:19:00,12/30/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-30 03:04:00,2015-12-30 05:19:00,0 days 02:15:00
2086,449252466,12/28/2015,18:00:00,12/28/2015,19:00:00,12/30/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-28 18:00:00,2015-12-28 19:00:00,0 days 01:00:00
2269,841076951,11/27/2015,20:00:00,NaN,NaN,12/30/2015,104,RAPE,153.0,RAPE 3,...,NaN,MANHATTANVILLE,NaN,NaN,NaN,NaN,NaN,2015-11-27 20:00:00,NaT,NaT
2716,462568423,12/29/2015,15:30:00,NaN,NaN,12/29/2015,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-29 15:30:00,NaT,NaT
3199,632341905,12/28/2015,20:00:00,12/28/2015,20:30:00,12/29/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-28 20:00:00,2015-12-28 20:30:00,0 days 00:30:00
3346,706551270,12/26/2015,02:30:00,12/26/2015,06:00:00,12/29/2015,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-26 02:30:00,2015-12-26 06:00:00,0 days 03:30:00
4024,994921451,12/27/2015,21:30:00,12/27/2015,22:00:00,12/28/2015,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-27 21:30:00,2015-12-27 22:00:00,0 days 00:30:00
4281,646084375,12/28/2015,02:40:00,12/28/2015,03:00:00,12/28/2015,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-28 02:40:00,2015-12-28 03:00:00,0 days 00:20:00
5617,139481182,12/27/2015,01:00:00,12/27/2015,01:20:00,12/27/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-27 01:00:00,2015-12-27 01:20:00,0 days 00:20:00
5674,621813268,12/26/2015,23:30:00,NaN,NaN,12/27/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-26 23:30:00,NaT,NaT
5686,181372401,12/26/2015,23:00:00,12/27/2015,06:40:00,12/27/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-26 23:00:00,2015-12-27 06:40:00,0 days 07:40:00
5879,438169439,12/25/2015,06:00:00,12/25/2015,09:00:00,12/27/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-25 06:00:00,2015-12-25 09:00:00,0 days 03:00:00
5885,472968111,12/25/2015,02:00:00,12/25/2015,03:00:00,12/27/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-25 02:00:00,2015-12-25 03:00:00,0 days 01:00:00
5991,448202906,11/03/2015,12:00:00,11/03/2015,13:00:00,12/27/2015,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-11-03 12:00:00,2015-11-03 13:00:00,0 days 01:00:00
6015,628688223,07/20/2015,12:00:00,NaN,NaN,12/27/2015,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-07-20 12:00:00,NaT,NaT
6576,651135996,12/26/2015,09:25:00,12/26/2015,09:30:00,12/26/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-26 09:25:00,2015-12-26 09:30:00,0 days 00:05:00
6634,279632944,12/26/2015,05:00:00,NaN,NaN,12/26/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-26 05:00:00,NaT,NaT
7601,313805073,12/25/2015,04:00:00,12/25/2015,04:30:00,12/25/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-25 04:00:00,2015-12-25 04:30:00,0 days 00:30:00
7602,488490546,12/25/2015,02:30:00,12/25/2015,06:00:00,12/25/2015,104,RAPE,157.0,RAPE 1,...,FORT GREENE PARK,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-25 02:30:00,2015-12-25 06:00:00,0 days 03:30:00
7853,582000545,12/24/2015,17:30:00,12/25/2015,07:30:00,12/25/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-24 17:30:00,2015-12-25 07:30:00,0 days 14:00:00
7874,604012954,10/12/2015,00:01:00,10/12/2015,23:59:00,12/19/2015,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-10-12 00:01:00,2015-10-12 23:59:00,0 days 23:58:00
8118,546749201,12/24/2015,18:00:00,12/24/2015,18:30:00,12/24/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-24 18:00:00,2015-12-24 18:30:00,0 days 00:30:00
8565,543298286,12/24/2015,03:25:00,12/24/2015,03:40:00,12/24/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-12-24 03:25:00,2015-12-24 03:40:00,0 days 00:15:00
9134,177516683,11/19/2015,23:00:00,11/19/2015,23:59:00,12/16/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-11-19 23:00:00,2015-11-19 23:59:00,0 days 00:59:00
10186,509053834,10/01/2015,12:00:00,10/31/2015,12:00:00,12/23/2015,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-10-01 12:00:00,2015-10-31 12:00:00,30 days 00:00:00
10201,550344851,06/03/2015,01:00:00,06/03/2015,02:00:00,12/23/2015,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-06-03 01:00:00,2015-06-03 02:00:00,0 days 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6040310,972316045,01/01/2017,00:01:00,01/05/2017,23:59:00,01/08/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-01 00:01:00,2017-01-05 23:59:00,4 days 23:58:00
6040425,926840989,01/07/2017,21:00:00,NaN,NaN,01/07/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-07 21:00:00,NaT,NaT
6040838,167132012,01/07/2017,04:00:00,01/07/2017,05:45:00,01/07/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-07 04:00:00,2017-01-07 05:45:00,0 days 01:45:00
6041810,559562266,01/06/2017,10:00:00,01/06/2017,10:20:00,01/06/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-06 10:00:00,2017-01-06 10:20:00,0 days 00:20:00
6042022,316742108,01/06/2017,00:15:00,NaN,NaN,01/06/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-06 00:15:00,NaT,NaT
6042246,940269397,01/04/2017,13:00:00,01/04/2017,15:00:00,01/06/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-04 13:00:00,2017-01-04 15:00:00,0 days 02:00:00
6042481,771559023,01/06/2016,17:30:00,NaN,NaN,01/06/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-06 17:30:00,NaT,NaT
6043297,702852795,01/05/2017,01:10:00,01/05/2017,01:30:00,01/05/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-05 01:10:00,2017-01-05 01:30:00,0 days 00:20:00
6043679,701108331,12/28/2016,08:00:00,12/28/2016,08:30:00,01/05/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-28 08:00:00,2016-12-28 08:30:00,0 days 00:30:00
6043850,154459729,08/01/2015,00:01:00,08/31/2015,23:59:00,01/05/2017,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-08-01 00:01:00,2015-08-31 23:59:00,30 days 23:58:00
6043853,323823903,07/07/2013,08:00:00,07/07/2014,08:00:00,01/05/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-07-07 08:00:00,2014-07-07 08:00:00,365 days 00:00:00
6044850,675886498,01/03/2017,15:30:00,01/03/2017,16:15:00,01/04/2017,104,RAPE,157.0,RAPE 1,...,NaN,ADAMS,NaN,NaN,NaN,NaN,NaN,2017-01-03 15:30:00,2017-01-03 16:15:00,0 days 00:45:00
6045256,367643547,12/14/2014,18:00:00,01/09/2015,15:00:00,01/04/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-12-14 18:00:00,2015-01-09 15:00:00,25 days 21:00:00
6045257,632841445,07/28/2013,02:00:00,07/28/2013,02:30:00,01/04/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-07-28 02:00:00,2013-07-28 02:30:00,0 days 00:30:00
6045948,552188042,01/03/2017,03:00:00,01/03/2017,03:30:00,01/03/2017,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-03 03:00:00,2017-01-03 03:30:00,0 days 00:30:00
6045964,112199910,01/03/2017,02:15:00,01/03/2017,03:30:00,01/03/2017,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-03 02:15:00,2017-01-03 03:30:00,0 days 01:15:00
6045989,621378019,01/03/2017,01:00:00,01/03/2017,01:30:00,01/03/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-03 01:00:00,2017-01-03 01:30:00,0 days 00:30:00
6046089,485703034,01/02/2017,19:30:00,NaN,NaN,01/03/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-02 19:30:00,NaT,NaT
6046316,839785044,12/28/2016,02:00:00,12/28/2016,02:30:00,01/03/2017,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-28 02:00:00,2016-12-28 02:30:00,0 days 00:30:00
6046505,516701965,06/01/2016,00:00:00,07/30/2016,00:00:00,01/03/2017,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-06-01 00:00:00,2016-07-30 00:00:00,59 days 00:00:00
6047219,354182596,01/01/2017,23:35:00,01/01/2017,23:54:00,01/02/2017,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-01 23:35:00,2017-01-01 23:54:00,0 days 00:19:00
6047380,470690353,01/01/2017,02:30:00,01/01/2017,12:30:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-01 02:30:00,2017-01-01 12:30:00,0 days 10:00:00
6047433,342860150,12/31/2016,00:20:00,12/31/2016,00:20:00,01/02/2017,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-31 00:20:00,2016-12-31 00:20:00,0 days 00:00:00
6047599,344368026,10/26/2016,09:00:00,10/26/2016,15:00:00,01/02/2017,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-10-26 09:00:00,2016-10-26 15:00:00,0 days 06:00:00
6047627,875232609,09/01/2011,00:00:00,11/01/2012,00:00:00,01/02/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-09-01 00:00:00,2012-11-01 00:00:00,427 days 00:00:00
6048179,108254204,01/01/2017,05:00:00,01/01/2017,06:00:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-01 05:00:00,2017-01-01 06:00:00,0 days 01:00:00
6048486,895568117,01/01/2017,01:00:00,01/01/2017,02:00:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-01 01:00:00,2017-01-01 02:00:00,0 days 01:00:00
6048513,629297118,01/01/2017,00:30:00,01/01/2017,00:55:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-01-01 00:30:00,2017-01-01 00:55:00,0 days 00:25:00
6048726,376969658,12/29/2016,23:00:00,12/30/2016,10:00:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-29 23:00:00,2016-12-30 10:00:00,0 days 11:00:00
6048795,329336049,10/01/2012,00:01:00,10/01/2012,00:01:00,01/01/2017,104,RAPE,153.0,RAPE 3,...,NaN,DOUGLASS,NaN,NaN,NaN,NaN,NaN,2012-10-01 00:01:00,2012-10-01 00:01:00,0 days 00:00:00

In [64]:
# Locate the rows where something is true, target the column, replace with value on right side of the equal size

df_rape.loc[df_rape['CMPLNT_FR_DT'].isna(), 'CMPLNT_FR_DT'] = df_rape.loc[df_rape['CMPLNT_FR_DT'].isna(), #something

SyntaxError: unexpected EOF while parsing (<ipython-input-64-b7893a755dcc>, line 3)

# Time Investigation

In [124]:
# Delete this column
df_rape['CRIME_DURATION'].isnull().sum()

3612

In [69]:
# Potential categorical variable with:
# * 0 - 30 minutes
# * 31 - 60 minutes
# 61 - 90 minutes
# 91 - 120 minutes
# 121 - 180 minutes
# 1 - 180 minutes
# ... find out if this is correlated to outcome variable

df_rape['CRIME_DURATION'].value_counts(ascending = False)

0 days 00:30:00       1207
0 days 01:00:00       1180
0 days 00:15:00        543
0 days 00:10:00        540
0 days 02:00:00        478
0 days 00:05:00        422
0 days 00:20:00        320
0 days 03:00:00        275
0 days 00:00:00        274
0 days 01:30:00        256
0 days 04:00:00        214
0 days 00:45:00        186
0 days 05:00:00        144
0 days 02:30:00        126
0 days 00:40:00        120
0 days 07:00:00        105
0 days 06:00:00        100
0 days 00:25:00         96
0 days 23:58:00         91
0 days 03:30:00         84
0 days 08:00:00         71
0 days 00:50:00         58
0 days 09:00:00         56
0 days 10:00:00         54
0 days 00:35:00         53
0 days 05:30:00         51
0 days 04:30:00         50
0 days 01:15:00         46
30 days 23:58:00        43
0 days 06:30:00         40
                      ...
44 days 08:00:00         1
4662 days 16:30:00       1
176 days 22:15:00        1
1041 days 19:59:00       1
205 days 23:58:00        1
116 days 00:00:00        1
6 days 20:40:00          1
0 days 03:23:00          1
396 days 04:00:00        1
0 days 13:05:00          1
273 days 05:00:00        1
1670 days 00:00:00       1
0 days 23:35:00          1
0 days 08:56:00          1
123 days 09:00:00        1
1093 days 23:59:00       1
0 days 19:10:00          1
293 days 23:58:00        1
4 days 11:00:00          1
73 days 01:49:00         1
22 days 09:00:00         1
1826 days 23:59:00       1
31 days 08:00:00         1
103 days 00:00:00        1
187 days 16:48:00        1
365 days 06:00:00        1
163 days 23:58:00        1
42 days 02:45:00         1
664 days 18:19:00        1
449 days 23:58:00        1
Name: CRIME_DURATION, Length: 2913, dtype: int64

In [72]:
# 10 pm - 4 am are dangers hours- how does each hour bucket compare to 
# outcome variable? Change to % of total

df_rape['CMPLNT_FR_DATETIME'].dt.hour.value_counts(ascending = False)

0     2429
12     995
23     920
2      878
1      845
3      805
22     762
4      742
20     709
15     708
16     671
21     641
18     619
8      617
5      523
17     514
19     491
14     485
9      427
13     399
6      395
10     395
11     377
7      326
Name: CMPLNT_FR_DATETIME, dtype: int64

In [75]:
df_rape['CMPLNT_FR_DATETIME'].describe()

count                   16673
unique                  15157
top       2005-01-01 00:01:00
freq                       23
first     1967-01-01 12:00:00
last      2017-12-29 03:30:00
Name: CMPLNT_FR_DATETIME, dtype: object

In [96]:
df_rape['CRIME_DURATION'].dt.seconds.value_counts(ascending = False)

3600.0     1317
1800.0     1270
0.0        1169
86280.0     679
7200.0      568
900.0       554
600.0       550
300.0       424
10800.0     353
1200.0      328
14400.0     281
5400.0      276
18000.0     198
2700.0      192
25200.0     160
21600.0     152
9000.0      145
2400.0      125
28800.0     124
1500.0       98
12600.0      95
86340.0      95
32400.0      89
36000.0      77
54000.0      73
43200.0      70
39600.0      69
50400.0      67
46800.0      61
19800.0      61
           ...
24060.0       1
16440.0       1
26160.0       1
38400.0       1
75780.0       1
84000.0       1
79920.0       1
60360.0       1
46020.0       1
35040.0       1
37740.0       1
17820.0       1
33540.0       1
23640.0       1
45900.0       1
58200.0       1
83640.0       1
28080.0       1
34560.0       1
52080.0       1
33720.0       1
33660.0       1
50940.0       1
62340.0       1
60300.0       1
20940.0       1
56220.0       1
52140.0       1
14880.0       1
47100.0       1
Name: CRIME_DURATION, Length: 656, dtype: int64

In [97]:
df_rape['CRIME_DURATION'].dt.seconds

21         21600.0
252            0.0
821        18000.0
1079       80640.0
1754        8100.0
2086        3600.0
2269           NaN
2716           NaN
3199        1800.0
3346       12600.0
4024        1800.0
4281        1200.0
5617        1200.0
5674           NaN
5686       27600.0
5879       10800.0
5885        3600.0
5991        3600.0
6015           NaN
6576         300.0
6634           NaN
7601        1800.0
7602       12600.0
7853       50400.0
7874       86280.0
8118        1800.0
8565         900.0
9134        3540.0
10186          0.0
10201       3600.0
            ...
6040310    86280.0
6040425        NaN
6040838     6300.0
6041810     1200.0
6042022        NaN
6042246     7200.0
6042481        NaN
6043297     1200.0
6043679     1800.0
6043850    86280.0
6043853        0.0
6044850     2700.0
6045256    75600.0
6045257     1800.0
6045948     1800.0
6045964     4500.0
6045989     1800.0
6046089        NaN
6046316     1800.0
6046505        0.0
6047219     1140.0
6047380    36000.0
6047433        0.0
6047599    21600.0
6047627        0.0
6048179     3600.0
6048486     3600.0
6048513     1500.0
6048726    39600.0
6048795        0.0
Name: CRIME_DURATION, Length: 16673, dtype: float64

In [94]:
df_rape['DURATION_IN_SECONDS'] = df_rape['CRIME_DURATION'].dt.seconds

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [98]:
df_rape['DURATION_IN_SECONDS']

21         21600.0
252            0.0
821        18000.0
1079       80640.0
1754        8100.0
2086        3600.0
2269           NaN
2716           NaN
3199        1800.0
3346       12600.0
4024        1800.0
4281        1200.0
5617        1200.0
5674           NaN
5686       27600.0
5879       10800.0
5885        3600.0
5991        3600.0
6015           NaN
6576         300.0
6634           NaN
7601        1800.0
7602       12600.0
7853       50400.0
7874       86280.0
8118        1800.0
8565         900.0
9134        3540.0
10186          0.0
10201       3600.0
            ...
6040310    86280.0
6040425        NaN
6040838     6300.0
6041810     1200.0
6042022        NaN
6042246     7200.0
6042481        NaN
6043297     1200.0
6043679     1800.0
6043850    86280.0
6043853        0.0
6044850     2700.0
6045256    75600.0
6045257     1800.0
6045948     1800.0
6045964     4500.0
6045989     1800.0
6046089        NaN
6046316     1800.0
6046505        0.0
6047219     1140.0
6047380    36000.0
6047433        0.0
6047599    21600.0
6047627        0.0
6048179     3600.0
6048486     3600.0
6048513     1500.0
6048726    39600.0
6048795        0.0
Name: DURATION_IN_SECONDS, Length: 16673, dtype: float64

In [99]:
df_rape['DURATION_IN_MINUTES'] = df_rape['DURATION_IN_SECONDS']/60

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [101]:
df_rape['DURATION_IN_MINUTES'].value_counts(ascending = False)

60.000000      1317
30.000000      1270
0.000000       1169
1438.000000     679
120.000000      568
15.000000       554
10.000000       550
5.000000        424
180.000000      353
20.000000       328
240.000000      281
90.000000       276
300.000000      198
45.000000       192
420.000000      160
360.000000      152
150.000000      145
40.000000       125
480.000000      124
25.000000        98
210.000000       95
1439.000000      95
540.000000       89
600.000000       77
900.000000       73
720.000000       70
660.000000       69
840.000000       67
780.000000       61
330.000000       61
               ...
298.000000        1
187.000000        1
697.000000        1
868.000000        1
924.000000        1
349.000000        1
763.000000        1
431.000000        1
116.000000        1
322.000000        1
560.000000        1
597.000000        1
479.983333        1
242.000000        1
700.000000        1
436.000000        1
378.000000        1
683.000000        1
1201.000000       1
466.000000        1
783.000000        1
1434.983333       1
395.000000        1
445.000000        1
1217.000000       1
1240.000000       1
213.000000        1
925.000000        1
455.000000        1
760.000000        1
Name: DURATION_IN_MINUTES, Length: 656, dtype: int64

In [102]:
df_rape['DURATION_IN_HOURS'] = df_rape['DURATION_IN_SECONDS']/3600

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [103]:
# Again, may put in buckets for categorical values

df_rape['DURATION_IN_HOURS'].value_counts(ascending = False)

1.000000     1317
0.500000     1270
0.000000     1169
23.966667     679
2.000000      568
0.250000      554
0.166667      550
0.083333      424
3.000000      353
0.333333      328
4.000000      281
1.500000      276
5.000000      198
0.750000      192
7.000000      160
6.000000      152
2.500000      145
0.666667      125
8.000000      124
0.416667       98
23.983333      95
3.500000       95
9.000000       89
10.000000      77
15.000000      73
12.000000      70
11.000000      69
14.000000      67
13.000000      61
5.500000       61
             ...
13.050000       1
23.883333       1
10.483333       1
20.016667       1
23.233333       1
16.516667       1
13.233333       1
14.433333       1
14.666667       1
22.966667       1
15.416667       1
7.300000        1
5.316667        1
3.383333        1
13.466667       1
2.966667        1
8.816667        1
17.616667       1
10.283333       1
12.150000       1
23.916389       1
7.583333        1
7.700000        1
21.050000       1
15.466667       1
19.116667       1
8.783333        1
18.400000       1
15.016667       1
6.650000        1
Name: DURATION_IN_HOURS, Length: 656, dtype: int64

In [104]:
df_rape

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,RPT_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,...,Y_COORD_CD,Latitude,Longitude,Lat_Lon,CMPLNT_FR_DATETIME,CMPLNT_TO_DATETIME,CRIME_DURATION,DURATION_IN_SECONDS,DURATION_IN_MINUTES,DURATION_IN_HOURS
21,340513307,04/06/2015,12:00:00,04/10/2015,18:00:00,12/21/2015,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,2015-04-06 12:00:00,2015-04-10 18:00:00,4 days 06:00:00,21600.0,360.0,6.000000
252,198273659,12/01/2009,10:00:00,01/01/2010,10:00:00,12/07/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2009-12-01 10:00:00,2010-01-01 10:00:00,31 days 00:00:00,0.0,0.0,0.000000
821,591506102,12/30/2015,18:00:00,12/30/2015,23:00:00,12/31/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2015-12-30 18:00:00,2015-12-30 23:00:00,0 days 05:00:00,18000.0,300.0,5.000000
1079,283109223,08/01/2015,00:01:00,12/30/2015,22:25:00,12/31/2015,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,2015-08-01 00:01:00,2015-12-30 22:25:00,151 days 22:24:00,80640.0,1344.0,22.400000
1754,361697946,12/30/2015,03:04:00,12/30/2015,05:19:00,12/30/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2015-12-30 03:04:00,2015-12-30 05:19:00,0 days 02:15:00,8100.0,135.0,2.250000
2086,449252466,12/28/2015,18:00:00,12/28/2015,19:00:00,12/30/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2015-12-28 18:00:00,2015-12-28 19:00:00,0 days 01:00:00,3600.0,60.0,1.000000
2269,841076951,11/27/2015,20:00:00,NaN,NaN,12/30/2015,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,2015-11-27 20:00:00,NaT,NaT,NaN,NaN,NaN
2716,462568423,12/29/2015,15:30:00,NaN,NaN,12/29/2015,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,NaN,NaN,NaN,NaN,2015-12-29 15:30:00,NaT,NaT,NaN,NaN,NaN
3199,632341905,12/28/2015,20:00:00,12/28/2015,20:30:00,12/29/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2015-12-28 20:00:00,2015-12-28 20:30:00,0 days 00:30:00,1800.0,30.0,0.500000
3346,706551270,12/26/2015,02:30:00,12/26/2015,06:00:00,12/29/2015,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,2015-12-26 02:30:00,2015-12-26 06:00:00,0 days 03:30:00,12600.0,210.0,3.500000
4024,994921451,12/27/2015,21:30:00,12/27/2015,22:00:00,12/28/2015,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,NaN,NaN,NaN,NaN,2015-12-27 21:30:00,2015-12-27 22:00:00,0 days 00:30:00,1800.0,30.0,0.500000
4281,646084375,12/28/2015,02:40:00,12/28/2015,03:00:00,12/28/2015,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,2015-12-28 02:40:00,2015-12-28 03:00:00,0 days 00:20:00,1200.0,20.0,0.333333
5617,139481182,12/27/2015,01:00:00,12/27/2015,01:20:00,12/27/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2015-12-27 01:00:00,2015-12-27 01:20:00,0 days 00:20:00,1200.0,20.0,0.333333
5674,621813268,12/26/2015,23:30:00,NaN,NaN,12/27/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2015-12-26 23:30:00,NaT,NaT,NaN,NaN,NaN
5686,181372401,12/26/2015,23:00:00,12/27/2015,06:40:00,12/27/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2015-12-26 23:00:00,2015-12-27 06:40:00,0 days 07:40:00,27600.0,460.0,7.666667
5879,438169439,12/25/2015,06:00:00,12/25/2015,09:00:00,12/27/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2015-12-25 06:00:00,2015-12-25 09:00:00,0 days 03:00:00,10800.0,180.0,3.000000
5885,472968111,12/25/2015,02:00:00,12/25/2015,03:00:00,12/27/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2015-12-25 02:00:00,2015-12-25 03:00:00,0 days 01:00:00,3600.0,60.0,1.000000
5991,448202906,11/03/2015,12:00:00,11/03/2015,13:00:00,12/27/2015,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,2015-11-03 12:00:00,2015-11-03 13:00:00,0 days 01:00:00,3600.0,60.0,1.000000
6015,628688223,07/20/2015,12:00:00,NaN,NaN,12/27/2015,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,2015-07-20 12:00:00,NaT,NaT,NaN,NaN,NaN
6576,651135996,12/26/2015,09:25:00,12/26/2015,09:30:00,12/26/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2015-12-26 09:25:00,2015-12-26 09:30:00,0 days 00:05:00,300.0,5.0,0.083333
6634,279632944,12/26/2015,05:00:00,NaN,NaN,12/26/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2015-12-26 05:00:00,NaT,NaT,NaN,NaN,NaN
7601,313805073,12/25/2015,04:00:00,12/25/2015,04:30:00,12/25/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2015-12-25 04:00:00,2015-12-25 04:30:00,0 days 00:30:00,1800.0,30.0,0.500000
7602,488490546,12/25/2015,02:30:00,12/25/2015,06:00:00,12/25/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2015-12-25 02:30:00,2015-12-25 06:00:00,0 days 03:30:00,12600.0,210.0,3.500000
7853,582000545,12/24/2015,17:30:00,12/25/2015,07:30:00,12/25/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2015-12-24 17:30:00,2015-12-25 07:30:00,0 days 14:00:00,50400.0,840.0,14.000000
7874,604012954,10/12/2015,00:01:00,10/12/2015,23:59:00,12/19/2015,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,2015-10-12 00:01:00,2015-10-12 23:59:00,0 days 23:58:00,86280.0,1438.0,23.966667
8118,546749201,12/24/2015,18:00:00,12/24/2015,18:30:00,12/24/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2015-12-24 18:00:00,2015-12-24 18:30:00,0 days 00:30:00,1800.0,30.0,0.500000
8565,543298286,12/24/2015,03:25:00,12/24/2015,03:40:00,12/24/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2015-12-24 03:25:00,2015-12-24 03:40:00,0 days 00:15:00,900.0,15.0,0.250000
9134,177516683,11/19/2015,23:00:00,11/19/2015,23:59:00,12/16/2015,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2015-11-19 23:00:00,2015-11-19 23:59:00,0 days 00:59:00,3540.0,59.0,0.983333
10186,509053834,10/01/2015,12:00:00,10/31/2015,12:00:00,12/23/2015,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,2015-10-01 12:00:00,2015-10-31 12:00:00,30 days 00:00:00,0.0,0.0,0.000000
10201,550344851,06/03/2015,01:00:00,06/03/2015,02:00:00,12/23/2015,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,2015-06-03 01:00:00,2015-06-03 02:00:00,0 days 01:00:00,3600.0,60.0,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6040310,972316045,01/01/2017,00:01:00,01/05/2017,23:59:00,01/08/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2017-01-01 00:01:00,2017-01-05 23:59:00,4 days 23:58:00,86280.0,1438.0,23.966667
6040425,926840989,01/07/2017,21:00:00,NaN,NaN,01/07/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2017-01-07 21:00:00,NaT,NaT,NaN,NaN,NaN
6040838,167132012,01/07/2017,04:00:00,01/07/2017,05:45:00,01/07/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2017-01-07 04:00:00,2017-01-07 05:45:00,0 days 01:45:00,6300.0,105.0,1.750000
6041810,559562266,01/06/2017,10:00:00,01/06/2017,10:20:00,01/06/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2017-01-06 10:00:00,2017-01-06 10:20:00,0 days 00:20:00,1200.0,20.0,0.333333
6042022,316742108,01/06/2017,00:15:00,NaN,NaN,01/06/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2017-01-06 00:15:00,NaT,NaT,NaN,NaN,NaN
6042246,940269397,01/04/2017,13:00:00,01/04/2017,15:00:00,01/06/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2017-01-04 13:00:00,2017-01-04 15:00:00,0 days 02:00:00,7200.0,120.0,2.000000
6042481,771559023,01/06/2016,17:30:00,NaN,NaN,01/06/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2016-01-06 17:30:00,NaT,NaT,NaN,NaN,NaN
6043297,702852795,01/05/2017,01:10:00,01/05/2017,01:30:00,01/05/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2017-01-05 01:10:00,2017-01-05 01:30:00,0 days 00:20:00,1200.0,20.0,0.333333
6043679,701108331,12/28/2016,08:00:00,12/28/2016,08:30:00,01/05/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2016-12-28 08:00:00,2016-12-28 08:30:00,0 days 00:30:00,1800.0,30.0,0.500000
6043850,154459729,08/01/2015,00:01:00,08/31/2015,23:59:00,01/05/2017,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,2015-08-01 00:01:00,2015-08-31 23:59:00,30 days 23:58:00,86280.0,1438.0,23.966667
6043853,323823903,07/07/2013,08:00:00,07/07/2014,08:00:00,01/05/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2013-07-07 08:00:00,2014-07-07 08:00:00,365 days 00:00:00,0.0,0.0,0.000000
6044850,675886498,01/03/2017,15:30:00,01/03/2017,16:15:00,01/04/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2017-01-03 15:30:00,2017-01-03 16:15:00,0 days 00:45:00,2700.0,45.0,0.750000
6045256,367643547,12/14/2014,18:00:00,01/09/2015,15:00:00,01/04/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2014-12-14 18:00:00,2015-01-09 15:00:00,25 days 21:00:00,75600.0,1260.0,21.000000
6045257,632841445,07/28/2013,02:00:00,07/28/2013,02:30:00,01/04/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2013-07-28 02:00:00,2013-07-28 02:30:00,0 days 00:30:00,1800.0,30.0,0.500000
6045948,552188042,01/03/2017,03:00:00,01/03/2017,03:30:00,01/03/2017,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,NaN,NaN,NaN,NaN,2017-01-03 03:00:00,2017-01-03 03:30:00,0 days 00:30:00,1800.0,30.0,0.500000
6045964,112199910,01/03/2017,02:15:00,01/03/2017,03:30:00,01/03/2017,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,2017-01-03 02:15:00,2017-01-03 03:30:00,0 days 01:15:00,4500.0,75.0,1.250000
6045989,621378019,01/03/2017,01:00:00,01/03/2017,01:30:00,01/03/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2017-01-03 01:00:00,2017-01-03 01:30:00,0 days 00:30:00,1800.0,30.0,0.500000
6046089,485703034,01/02/2017,19:30:00,NaN,NaN,01/03/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2017-01-02 19:30:00,NaT,NaT,NaN,NaN,NaN
6046316,839785044,12/28/2016,02:00:00,12/28/2016,02:30:00,01/03/2017,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,2016-12-28 02:00:00,2016-12-28 02:30:00,0 days 00:30:00,1800.0,30.0,0.500000
6046505,516701965,06/01/2016,00:00:00,07/30/2016,00:00:00,01/03/2017,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,2016-06-01 00:00:00,2016-07-30 00:00:00,59 days 00:00:00,0.0,0.0,0.000000
6047219,354182596,01/01/2017,23:35:00,01/01/2017,23:54:00,01/02/2017,104,RAPE,159.0,"RAPE 1,ATTEMPT",...,NaN,NaN,NaN,NaN,2017-01-01 23:35:00,2017-01-01 23:54:00,0 days 00:19:00,1140.0,19.0,0.316667
6047380,470690353,01/01/2017,02:30:00,01/01/2017,12:30:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2017-01-01 02:30:00,2017-01-01 12:30:00,0 days 10:00:00,36000.0,600.0,10.000000
6047433,342860150,12/31/2016,00:20:00,12/31/2016,00:20:00,01/02/2017,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,2016-12-31 00:20:00,2016-12-31 00:20:00,0 days 00:00:00,0.0,0.0,0.000000
6047599,344368026,10/26/2016,09:00:00,10/26/2016,15:00:00,01/02/2017,104,RAPE,155.0,RAPE 2,...,NaN,NaN,NaN,NaN,2016-10-26 09:00:00,2016-10-26 15:00:00,0 days 06:00:00,21600.0,360.0,6.000000
6047627,875232609,09/01/2011,00:00:00,11/01/2012,00:00:00,01/02/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2011-09-01 00:00:00,2012-11-01 00:00:00,427 days 00:00:00,0.0,0.0,0.000000
6048179,108254204,01/01/2017,05:00:00,01/01/2017,06:00:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2017-01-01 05:00:00,2017-01-01 06:00:00,0 days 01:00:00,3600.0,60.0,1.000000
6048486,895568117,01/01/2017,01:00:00,01/01/2017,02:00:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2017-01-01 01:00:00,2017-01-01 02:00:00,0 days 01:00:00,3600.0,60.0,1.000000
6048513,629297118,01/01/2017,00:30:00,01/01/2017,00:55:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2017-01-01 00:30:00,2017-01-01 00:55:00,0 days 00:25:00,1500.0,25.0,0.416667
6048726,376969658,12/29/2016,23:00:00,12/30/2016,10:00:00,01/01/2017,104,RAPE,157.0,RAPE 1,...,NaN,NaN,NaN,NaN,2016-12-29 23:00:00,2016-12-30 10:00:00,0 days 11:00:00,39600.0,660.0,11.000000
6048795,329336049,10/01/2012,00:01:00,10/01/2012,00:01:00,01/01/2017,104,RAPE,153.0,RAPE 3,...,NaN,NaN,NaN,NaN,2012-10-01 00:01:00,2012-10-01 00:01:00,0 days 00:00:00,0.0,0.0,0.000000

In [111]:
# Convert to datetime for more calculations
type(df_rape['RPT_DT'][21])

pandas._libs.tslib.Timestamp

In [109]:
df_rape['RPT_DT']

21        2015-12-21
252       2015-12-07
821       2015-12-31
1079      2015-12-31
1754      2015-12-30
2086      2015-12-30
2269      2015-12-30
2716      2015-12-29
3199      2015-12-29
3346      2015-12-29
4024      2015-12-28
4281      2015-12-28
5617      2015-12-27
5674      2015-12-27
5686      2015-12-27
5879      2015-12-27
5885      2015-12-27
5991      2015-12-27
6015      2015-12-27
6576      2015-12-26
6634      2015-12-26
7601      2015-12-25
7602      2015-12-25
7853      2015-12-25
7874      2015-12-19
8118      2015-12-24
8565      2015-12-24
9134      2015-12-16
10186     2015-12-23
10201     2015-12-23
             ...
6040310   2017-01-08
6040425   2017-01-07
6040838   2017-01-07
6041810   2017-01-06
6042022   2017-01-06
6042246   2017-01-06
6042481   2017-01-06
6043297   2017-01-05
6043679   2017-01-05
6043850   2017-01-05
6043853   2017-01-05
6044850   2017-01-04
6045256   2017-01-04
6045257   2017-01-04
6045948   2017-01-03
6045964   2017-01-03
6045989   2017-01-03
6046089   2017-01-03
6046316   2017-01-03
6046505   2017-01-03
6047219   2017-01-02
6047380   2017-01-01
6047433   2017-01-02
6047599   2017-01-02
6047627   2017-01-02
6048179   2017-01-01
6048486   2017-01-01
6048513   2017-01-01
6048726   2017-01-01
6048795   2017-01-01
Name: RPT_DT, Length: 16673, dtype: datetime64[ns]

In [112]:
# Difference between report date and beginning of attemped/completed crime
df_rape['TIME_TO_REPORT'] = df_rape['RPT_DT'] - df_rape['CMPLNT_FR_DATETIME']

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [125]:
df_rape['TIME_TO_REPORT'].isnull().sum()

0

In [114]:
# Might 'bucketize' this- also, investigate relationship 
# to outcome variable
df_rape['TIME_TO_REPORT'].value_counts(ascending = False)

-1 days +21:00:00     275
-1 days +22:00:00     264
-1 days +20:00:00     239
-1 days +23:00:00     210
0 days 01:00:00       182
0 days 02:00:00       170
-1 days +19:00:00     169
-1 days +23:59:00     137
0 days 04:00:00       128
-1 days +18:00:00     126
0 days 03:00:00       125
-1 days +23:30:00     119
-1 days +19:30:00     114
-1 days +21:30:00     113
-1 days +20:30:00     105
-1 days +22:30:00     101
-1 days +12:00:00      97
-1 days +18:30:00      92
0 days 00:30:00        83
0 days 05:00:00        82
-1 days +16:00:00      81
0 days 06:00:00        80
-1 days +14:00:00      77
0 days 00:00:00        77
0 days 01:30:00        74
-1 days +11:00:00      73
-1 days +10:00:00      73
0 days 02:30:00        72
-1 days +08:00:00      71
0 days 07:00:00        70
                     ...
800 days 04:00:00       1
0 days 03:55:00         1
365 days 06:00:00       1
152 days 06:30:00       1
474 days 23:59:00       1
891 days 23:59:00       1
2840 days 09:00:00      1
893 days 23:59:00       1
692 days 16:00:00       1
361 days 21:00:00       1
273 days 05:00:00       1
2 days 09:10:00         1
2673 days 23:59:00      1
722 days 11:00:00       1
324 days 12:00:00       1
306 days 14:00:00       1
89 days 03:00:00        1
266 days 06:30:00       1
44 days 08:00:00        1
171 days 23:59:00       1
-1 days +17:38:00       1
5113 days 12:00:00      1
26 days 10:00:00        1
17 days 11:00:00        1
1259 days 12:00:00      1
-1 days +03:18:00       1
127 days 10:00:00       1
2194 days 12:00:00      1
2611 days 12:00:00      1
1331 days 15:00:00      1
Name: TIME_TO_REPORT, Length: 6120, dtype: int64

In [148]:
df_rape['LAW_CAT_CD'].value_counts(ascending = False)

FELONY    16673
Name: LAW_CAT_CD, dtype: int64

In [119]:
# This is meaningless, almost entirely police dept
df_rape['JURIS_DESC'].value_counts(ascending = False)

N.Y. POLICE DEPT       14728
N.Y. HOUSING POLICE     1824
N.Y. TRANSIT POLICE       41
POLICE DEPT NYC           16
OTHER                     15
PORT AUTHORITY            15
HEALTH & HOSP CORP        14
DEPT OF CORRECTIONS        7
N.Y. STATE POLICE          3
NYC PARKS                  3
METRO NORTH                3
AMTRACK                    2
N.Y. STATE PARKS           1
U.S. PARK POLICE           1
Name: JURIS_DESC, dtype: int64

In [120]:
# This is imbalance
df_rape['BORO_NM'].value_counts(ascending = False)

BROOKLYN         5002
QUEENS           3802
BRONX            3692
MANHATTAN        3530
STATEN ISLAND     643
Name: BORO_NM, dtype: int64

In [ ]:
# Make the above per capita
# Populations in 2017:
# Manhattan: 1.665 million
# Brooklyn: 2.649 million
# Queens: 2.359 million
# Bronx: 1.471 million
# Staten Island: 479,458

In [121]:
# Which years the crimes were committed, in case I need to think about
# subsets for an accurate analysis
# Looks like cutting data to 2006 - 2018 is more meaningful
df_rape['CMPLNT_FR_DATETIME'].dt.year.value_counts(ascending = False)

2006    1539
2011    1407
2012    1394
2010    1378
2013    1338
2015    1333
2007    1276
2016    1268
2008    1265
2014    1258
2009    1190
2017    1160
2005     316
2004     117
2003     102
2001      66
2002      64
2000      44
1999      44
1998      30
1997      15
1993      14
1996      12
1994       7
1995       5
1992       4
1991       3
1975       2
1989       2
1984       2
1983       2
1988       2
1990       2
1978       2
1986       2
1981       1
1967       1
1987       1
1980       1
1977       1
1976       1
1973       1
1968       1
Name: CMPLNT_FR_DATETIME, dtype: int64

In [122]:
df_rape['CMPLNT_FR_DATETIME'].dt.year.value_counts()

2006    1539
2011    1407
2012    1394
2010    1378
2013    1338
2015    1333
2007    1276
2016    1268
2008    1265
2014    1258
2009    1190
2017    1160
2005     316
2004     117
2003     102
2001      66
2002      64
2000      44
1999      44
1998      30
1997      15
1993      14
1996      12
1994       7
1995       5
1992       4
1991       3
1975       2
1989       2
1984       2
1983       2
1988       2
1990       2
1978       2
1986       2
1981       1
1967       1
1987       1
1980       1
1977       1
1976       1
1973       1
1968       1
Name: CMPLNT_FR_DATETIME, dtype: int64

In [127]:
df_rape.columns

Index(['CMPLNT_NUM', 'CMPLNT_FR_DT', 'CMPLNT_FR_TM', 'CMPLNT_TO_DT',
       'CMPLNT_TO_TM', 'RPT_DT', 'KY_CD', 'OFNS_DESC', 'PD_CD', 'PD_DESC',
       'CRM_ATPT_CPTD_CD', 'LAW_CAT_CD', 'JURIS_DESC', 'BORO_NM',
       'ADDR_PCT_CD', 'LOC_OF_OCCUR_DESC', 'PREM_TYP_DESC', 'PARKS_NM',
       'HADEVELOPT', 'X_COORD_CD', 'Y_COORD_CD', 'Latitude', 'Longitude',
       'Lat_Lon', 'CMPLNT_FR_DATETIME', 'CMPLNT_TO_DATETIME', 'CRIME_DURATION',
       'DURATION_IN_SECONDS', 'DURATION_IN_MINUTES', 'DURATION_IN_HOURS',
       'TIME_TO_REPORT'],
      dtype='object')

In [128]:
df_rape['KY_CD'].value_counts()

104    16673
Name: KY_CD, dtype: int64

In [129]:
df_rape['OFNS_DESC'].value_counts()

RAPE    16673
Name: OFNS_DESC, dtype: int64

In [130]:
df_rape['PD_CD'].value_counts()

157.0    10801
153.0     2242
159.0     1819
155.0     1811
Name: PD_CD, dtype: int64

In [131]:
df_rape['PD_DESC'].value_counts()

RAPE 1            10801
RAPE 3             2242
RAPE 1,ATTEMPT     1819
RAPE 2             1811
Name: PD_DESC, dtype: int64

In [ ]:
ADDR_PCT_CD', 'LOC_OF_OCCUR_DESC', 'PREM_TYP_DESC', 'PARKS_NM',
       'HADEVELOPT'

In [135]:
df_rape['ADDR_PCT_CD'].value_counts().shape

(77,)

In [136]:
df_rape['ADDR_PCT_CD'].value_counts()

75.0     701
115.0    431
43.0     431
120.0    426
47.0     425
67.0     417
73.0     412
44.0     411
46.0     386
83.0     379
110.0    370
103.0    365
40.0     361
32.0     341
105.0    338
42.0     326
52.0     324
114.0    319
79.0     318
113.0    316
48.0     302
70.0     283
25.0     264
102.0    260
23.0     256
77.0     250
34.0     229
30.0     229
81.0     228
49.0     227
        ...
18.0     150
14.0     147
19.0     139
24.0     131
66.0     130
63.0     129
26.0     129
61.0     128
62.0     128
7.0      127
10.0     123
50.0     121
6.0      121
122.0    117
1.0      108
88.0     107
68.0     106
17.0      99
20.0      95
94.0      87
5.0       86
78.0      79
100.0     79
112.0     77
121.0     66
76.0      65
84.0      59
111.0     53
123.0     34
22.0      25
Name: ADDR_PCT_CD, Length: 77, dtype: int64

In [137]:
# Discard
df_rape['LOC_OF_OCCUR_DESC'].value_counts()

INSIDE         14003
FRONT OF         780
REAR OF          218
OPPOSITE OF      117
Name: LOC_OF_OCCUR_DESC, dtype: int64

In [140]:
# Get_dummies on first five
df_rape['PREM_TYP_DESC'].value_counts().shape

(55,)

In [141]:
# Think about PCA
df_rape['PREM_TYP_DESC'].value_counts()

RESIDENCE - APT. HOUSE          8501
RESIDENCE-HOUSE                 3094
RESIDENCE - PUBLIC HOUSING      1782
STREET                          1029
HOTEL/MOTEL                      657
OTHER                            344
PARK/PLAYGROUND                  262
HOSPITAL                         126
BAR/NIGHT CLUB                   125
COMMERCIAL BUILDING              103
PUBLIC SCHOOL                     71
OPEN AREAS (OPEN LOTS)            52
PUBLIC BUILDING                   40
TRANSIT - NYC SUBWAY              38
RESTAURANT/DINER                  37
PARKING LOT/GARAGE (PUBLIC)       33
PARKING LOT/GARAGE (PRIVATE)      30
ABANDONED BUILDING                27
GROCERY/BODEGA                    27
CHURCH                            24
STORE UNCLASSIFIED                15
TAXI (YELLOW LICENSED)            15
SMALL MERCHANT                    12
FAST FOOD                         10
TAXI (LIVERY LICENSED)            10
SOCIAL CLUB/POLICY                10
BEAUTY & NAIL SALON               10
MARINA/PIER                        9
CLOTHING/BOUTIQUE                  9
BRIDGE                             9
CHAIN STORE                        8
HIGHWAY/PARKWAY                    8
DOCTOR/DENTIST OFFICE              8
PRIVATE/PAROCHIAL SCHOOL           7
DEPARTMENT STORE                   7
GYM/FITNESS FACILITY               6
DRY CLEANER/LAUNDRY                6
TRANSIT FACILITY (OTHER)           5
FACTORY/WAREHOUSE                  5
BUS (OTHER)                        5
CONSTRUCTION SITE                  5
BUS TERMINAL                       4
DRUG STORE                         3
AIRPORT TERMINAL                   3
FOOD SUPERMARKET                   2
VARIETY STORE                      2
BUS STOP                           2
CANDY STORE                        2
CEMETERY                           2
TAXI/LIVERY (UNLICENSED)           2
OTHER HOUSE OF WORSHIP             2
BANK                               2
STORAGE FACILITY                   1
MOSQUE                             1
JEWELRY                            1
Name: PREM_TYP_DESC, dtype: int64

In [ ]:
'PARKS_NM',
       'HADEVELOPT'

In [142]:
df_rape['PARKS_NM'].value_counts().shape

(56,)

In [143]:
# discard
df_rape['PARKS_NM'].value_counts()

CENTRAL PARK                                                           10
RIVERSIDE PARK                                                          5
PROSPECT PARK                                                           5
CONEY ISLAND BEACH & BOARDWALK                                          4
RUFUS KING PARK                                                         3
VAN CORTLANDT PARK                                                      3
BRONX PARK                                                              3
ROCKAWAY BEACH AND BOARDWALK                                            2
SOUNDVIEW PARK                                                          2
PELHAM BAY PARK                                                         2
TREMONT PARK                                                            2
RED HOOK RECREATION AREA                                                2
EAST RIVER PARK                                                         2
CROTONA PARK                                                            2
FLUSHING MEADOWS CORONA PARK                                            2
DYKER BEACH PARK                                                        1
STUYVESANT SQUARE                                                       1
KISSENA CORRIDOR PARK                                                   1
MCCARREN PARK                                                           1
HARLEM ART PARK                                                         1
HARLEM RIVER PARK                                                       1
LINDEN PARK                                                             1
ST. MARY'S PARK BRONX                                                   1
FORT TRYON PARK                                                         1
JOYCE KILMER PARK                                                       1
KISSENA PARK                                                            1
SETON FALLS PARK                                                        1
SAW MILL PLAYGROUND                                                     1
CALVERT VAUX PARK                                                       1
ST. ANDREW'S PLAYGROUND                                                 1
CANARSIE PARK                                                           1
BOWNE PLAYGROUND                                                        1
RICHMAN (ECHO) PARK                                                     1
DETECTIVE KEITH L WILLIAMS PARK                                         1
KAISER PARK                                                             1
MOUNT HOPE PLAYGROUND                                                   1
UNNAMED PARK ON PROSPECT EXPRESSWAY BETWEEN 3RD AVENUE & 7TH AVENUE     1
EHRENREICH-AUSTIN PLAYGROUND                                            1
MARIA HERNANDEZ PARK                                                    1
CARVER PLAYGROUND                                                       1
JAIME CAMPIZ PLAYGROUND                                                 1
CONCRETE PLANT PARK                                                     1
MARCUS GARVEY PARK                                                      1
LINDSAY TRIANGLE                                                        1
BENNETT PARK                                                            1
FOREST PARK                                                             1
GORMAN PARK                                                             1
CLOVE LAKES PARK                                                        1
BATTERY PARK                                                            1
ST. JOHN'S RECREATION CENTER                                            1
DR. RONALD E. MCNAIR PLAYGROUND                                         1
UNION SQUARE PARK                                                       1
OSBORN PLAYGROUND                                                       1
FORT GREENE PARK                                                        1
ST. NICHOLAS PARK                                                       1
CAPTAIN TILLY PARK                                                      1
Name: PARKS_NM, dtype: int64

In [144]:
df_rape['HADEVELOPT'].value_counts().shape

(201,)

In [145]:
#discard
df_rape['HADEVELOPT'].value_counts()

CASTLE HILL                                    28
VAN DYKE I                                     28
BUTLER                                         26
PINK                                           22
TOMPKINS                                       22
GRANT                                          20
SMITH                                          18
BROWNSVILLE                                    17
BARUCH                                         16
LINDEN                                         16
MARCY                                          16
MANHATTANVILLE                                 15
BOULEVARD                                      15
TILDEN                                         15
BUSHWICK                                       15
RANGEL                                         14
WHITMAN                                        14
CYPRESS HILLS                                  14
FARRAGUT                                       14
BRONXDALE                                      14
INGERSOLL                                      14
DOUGLASS                                       14
THROGGS NECK                                   13
ASTORIA                                        13
VLADECK                                        12
LAFAYETTE                                      12
BREVOORT                                       11
LA GUARDIA                                     11
POMONOK                                        11
GOWANUS                                        11
                                               ..
EAST 173RD STREET-VYSE AVENUE                   1
VANDALIA AVENUE                                 1
FRANKLIN AVENUE II CONVENTIONAL                 1
REID APARTMENTS                                 1
HARRISON AVENUE REHAB (GROUP A)                 1
WASHINGTON HEIGHTS REHAB PHASE III              1
FENIMORE-LEFFERTS                               1
HERNANDEZ                                       1
1162-1176 WASHINGTON AVENUE                     1
UPACA (SITE 6)                                  1
CROWN HEIGHTS                                   1
EAGLE AVENUE-EAST 163RD STREET                  1
FIORENTINO PLAZA                                1
STERLING PLACE REHAB (SAINT JOHNS-STERLING)     1
MARCY AVENUE-GREENE AVENUE SITE A               1
PARK ROCK REHAB                                 1
BREUKELEN                                       1
FORT WASHINGTON AVENUE REHAB                    1
BARUCH HOUSES ADDITION                          1
BUSHWICK II CDA (GROUP E)                       1
BAISLEY PARK                                    1
MILBANK-FRAWLEY                                 1
SAMUEL (CITY)                                   1
HARRISON AVENUE REHAB (GROUP B)                 1
RUTLAND TOWERS                                  1
WOODSON                                         1
303 VERNON AVENUE                               1
131 SAINT NICHOLAS AVENUE                       1
HOWARD AVENUE-PARK PLACE                        1
CLAREMONT REHAB (GROUP 4)                       1
Name: HADEVELOPT, Length: 201, dtype: int64